CREATE TABLE IF NOT EXISTS public.polling_protocol
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS public.access
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS public.version_snmp
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS public.auth_protocol_snmp
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS public.privacy_protocol_snmp
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS public.oid_type
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(17)
);

CREATE TABLE IF NOT EXISTS public.logic_operator
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(12) NOT NULL,
    "type" VARCHAR(15) NOT NULL,
    "precedence" SMALLINT NOT NULL,
    "arity" SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.alarm_level
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS public.var_type
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(17)
);

CREATE TABLE IF NOT EXISTS public.polling_frequency
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(6)
);

CREATE TABLE IF NOT EXISTS public.oid_access
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(21) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.oid_status
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.asn1_type
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.vendor
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "number" INTEGER NOT NULL,
    "contact" TEXT,
    "email" TEXT,
    "directory" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS public.component
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR NOT NULL,
    "name_en" VARCHAR NOT NULL,
    "name_ru" VARCHAR NOT NULL,
    "plural_name_en" VARCHAR NOT NULL,
    "plural_name_ru" VARCHAR NOT NULL,
    "base_component" BIGINT,
    "description_en" TEXT,
    "description_ru" TEXT,
    "access" SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.param
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR NOT NULL,
    "name_en" VARCHAR NOT NULL,
    "name_ru" VARCHAR NOT NULL,
    "type" SMALLINT NOT NULL,
    "value" TEXT,
    "description_en" TEXT,
    "description_ru" TEXT,
    "units_en" TEXT,
    "units_ru" TEXT,
    "access" SMALLINT NOT NULL,
    "saved" BOOLEAN NOT NULL,
    "visible" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS public.component_param
(
    "component_id" BIGINT NOT NULL,
    "param_id" BIGINT NOT NULL,
    PRIMARY KEY ("component_id", "param_id")
);

CREATE TABLE IF NOT EXISTS public.agent_capabilities
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "product_release" TEXT,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.agent_capabilities_module
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supports" VARCHAR(255),
    "includes" VARCHAR(255)[]
);

CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_notification
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "variation" VARCHAR(255),
    "access" SMALLINT,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_object
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "variation" VARCHAR(255),
    "syntax" VARCHAR(255),
    "write_syntax" VARCHAR(255),
    "access" SMALLINT,
    "creation_requires" VARCHAR(255)[],
    "defval" VARCHAR(255),
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS public.choice
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "choices" JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS public.explicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "value" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.implicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "application" SMALLINT NOT NULL,
    "value" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.import
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "param" VARCHAR(255) NOT NULL,
    "from" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "path" TEXT NOT NULL,
    "name" VARCHAR(50),
    "vendor" BIGINT
);

CREATE TABLE IF NOT EXISTS public.module_compliance
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.module_compliance_module
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "mandatory_groups" VARCHAR(255)[]
);

CREATE TABLE IF NOT EXISTS public.module_compliance_module_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS public.module_compliance_module_object
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "syntax" VARCHAR(255),
    "write_syntax" VARCHAR(255),
    "access" SMALLINT,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS public.module_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "last_updated" TIMESTAMP,
    "organization" VARCHAR(255),
    "contact_info" TEXT,
    "description"  TEXT
);

CREATE TABLE IF NOT EXISTS public.notification_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "notifications" VARCHAR(255)[],
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.notification_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "objects" VARCHAR(255)[],
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.object_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "objects" VARCHAR[],
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.object_identifier
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "num_oid" VARCHAR[],
    "str_oid" VARCHAR[],
    "parent" VARCHAR(255),
    "type" SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.object_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.object_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "syntax" TEXT,
    "units" VARCHAR(255),
    "access" SMALLINT,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT,
    "index" VARCHAR(255)[],
    "augments" VARCHAR(255)[],
    "default_value" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS public.oid
(
    "id" UUID PRIMARY KEY,
    "mib" BIGINT,
    "type" SMALLINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "number" INTEGER,
    "dotter_notation" TEXT NOT NULL,
    "object_descriptor" TEXT NOT NULL,
    "syntax" TEXT,
    "enum" JSONB,
    "status" SMALLINT,
    "access" SMALLINT,
    "units" VARCHAR(255),
    "description" TEXT,
    "category" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS public.revision
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "revision" TIMESTAMP,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS public.sequence
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "pairs" JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS public.textual_convention
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "display_hint" VARCHAR(255),
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT,
    "syntax" TEXT
);

CREATE TABLE IF NOT EXISTS public.trap_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "variables" VARCHAR(255)[],
    "description" TEXT,
    "reference" TEXT
);

CREATE TABLE IF NOT EXISTS public.mib_to_agent_capabilities
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "agent_capabilities_id" BIGINT NOT NULL,
    "agent_capabilities_module_id" BIGINT,
    "agent_capabilities_module_notification_id" BIGINT,
    "agent_capabilities_module_object_id" BIGINT
);

CREATE TABLE IF NOT EXISTS public.mib_to_choice
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "choice_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_explicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "explicit_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_implicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "implicit_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_import
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "import_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_module_compliance
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "module_compliance_id" BIGINT NOT NULL,
    "module_compliance_module_id" BIGINT,
    "module_compliance_module_group_id" BIGINT,
    "module_compliance_module_object_id" BIGINT
);

CREATE TABLE IF NOT EXISTS public.mib_to_module_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "module_identity_id" BIGINT NOT NULL,
    "revision_id" BIGINT
);

CREATE TABLE IF NOT EXISTS public.mib_to_notification_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "notification_group_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_notification_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "notification_type_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_object_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_group_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_object_identifier
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_identifier_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_object_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_identity_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_object_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_type_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_sequence
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "sequence_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_textual_convention
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "textual_convention_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mib_to_trap_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "trap_type_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.device_indicator
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "description" TEXT,
    "object_id" TEXT NOT NULL,
    "contact" TEXT,
    "name" TEXT,
    "location" TEXT,
    "services" SMALLINT
);

CREATE TABLE IF NOT EXISTS public.param_indicator
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "oid_id" UUID,
    "dotter_notation" TEXT
);

CREATE TABLE IF NOT EXISTS public.mapping
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indicator" BIGINT NOT NULL,
    "param" BIGINT NOT NULL,
    "frequency" SMALLINT NOT NULL,
    "value" VARCHAR(255),
    "coefficient" NUMERIC(38, 12),
    "enum" JSONB,
    "position" SMALLINT,
    "from" BIGINT,
    "position_type" SMALLINT
);

CREATE TABLE IF NOT EXISTS public.device_component
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "model" BIGINT NOT NULL,
    "internal_order" INTEGER DEFAULT 1,
    "parent" BIGINT
);

CREATE TABLE IF NOT EXISTS public.device_component_mapping
(
    "device_component_id" BIGINT NOT NULL,
    "mapping_id" BIGINT NOT NULL,
    PRIMARY KEY ("device_component_id", "mapping_id")
);

CREATE TABLE IF NOT EXISTS public.configuration
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indicator" BIGINT NOT NULL,
    "device_component_id" BIGINT
);

CREATE TABLE IF NOT EXISTS public.default_configuration
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indicator" BIGINT NOT NULL,
    "device_component_id" BIGINT
);

CREATE TABLE IF NOT EXISTS public.threshold
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR(255) NOT NULL,
    "description" TEXT,
    "author"      VARCHAR(255) NOT NULL,
    "created"     TIMESTAMP,
    "query"       JSONB        NOT NULL,
    "target"      JSONB        NOT NULL,
    "value"       TEXT         NOT NULL
);

CREATE TABLE IF NOT EXISTS public.device_snmp
(
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "community" VARCHAR(255) NOT NULL,
    "version" SMALLINT NOT NULL,
    "login" VARCHAR(255),
    "password" TEXT,
    "authentication" SMALLINT NOT NULL,
    "privacy" SMALLINT NOT NULL,
    "id" UUID UNIQUE NOT NULL,
    "config" BIGINT,
    PRIMARY KEY ("host", "port")
);

CREATE TABLE IF NOT EXISTS public.result
(
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "component" BIGINT NOT NULL,
    "internal_order" INTEGER DEFAULT 1,
    "param" BIGINT NOT NULL,
    "value" TEXT,
    PRIMARY KEY ("host", "port", "component", "internal_order", "param")
);

CREATE TABLE IF NOT EXISTS public.affected_threshold
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "threshold" BIGINT NOT NULL,
    "enabled" BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.affected_param
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "component" BIGINT NOT NULL,
    "internal_order" INTEGER DEFAULT 1,
    "param" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.config_in_process
(
    "host" VARCHAR(255) NOT NULL,
    "port" INTEGER NOT NULL,
    "protocol" SMALLINT NOT NULL,
    PRIMARY KEY ("host", "port", "protocol")
);

ALTER TABLE public.logic_operator
  ADD CONSTRAINT "logic_operator_value_key" UNIQUE ("value"),
  ADD CONSTRAINT "logic_operator_type_check" CHECK ("type" IN ('LOGICAL', 'COMPARISON', 'BRACKET')),
  ADD CONSTRAINT "logic_operator_arity_check" CHECK ("arity" IN (1, 2));

ALTER TABLE public.oid_access
  ADD CONSTRAINT "oid_access_value_key" UNIQUE ("value");

ALTER TABLE public.oid_status
  ADD CONSTRAINT "oid_status_value_key" UNIQUE ("value");

ALTER TABLE public.asn1_type
  ADD CONSTRAINT "asn1_type_value_key" UNIQUE ("value");

ALTER TABLE public.vendor
  ADD CONSTRAINT "vendor_number_key" UNIQUE ("number");

ALTER TABLE public.agent_capabilities
  ADD CONSTRAINT "agent_capabilities_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.agent_capabilities_module_notification
  ADD CONSTRAINT "agent_capabilities_module_notification_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.agent_capabilities_module_object
  ADD CONSTRAINT "agent_capabilities_module_object_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.mib
  ADD CONSTRAINT "mib_path_key" UNIQUE ("path"),
  ADD CONSTRAINT "mib_vendor_fkey" FOREIGN KEY ("vendor") REFERENCES public.vendor ("id") ON DELETE CASCADE;

ALTER TABLE public.module_compliance
  ADD CONSTRAINT "module_compliance_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.module_compliance_module_object
  ADD CONSTRAINT "module_compliance_module_object_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.notification_group
  ADD CONSTRAINT "notification_group_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.notification_type
  ADD CONSTRAINT "notification_type_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.object_group
  ADD CONSTRAINT "object_group_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.object_identifier
  ADD CONSTRAINT "object_identifier_type_fkey" FOREIGN KEY ("type") REFERENCES public.asn1_type ("id") ON DELETE CASCADE;

ALTER TABLE public.object_identity
  ADD CONSTRAINT "object_identity_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.object_type
  ADD CONSTRAINT "object_type_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "object_type_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.textual_convention
  ADD CONSTRAINT "textual_convention_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.mib_to_agent_capabilities
  ADD CONSTRAINT "mib_to_agent_capabilities_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_id_fkey" FOREIGN KEY ("agent_capabilities_id") REFERENCES public.agent_capabilities ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_module_id_fkey" FOREIGN KEY ("agent_capabilities_module_id") REFERENCES public.agent_capabilities_module ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_module_notification_id_fkey" FOREIGN KEY ("agent_capabilities_module_notification_id") REFERENCES public.agent_capabilities_module_notification ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_module_object_id_fkey" FOREIGN KEY ("agent_capabilities_module_object_id") REFERENCES public.agent_capabilities_module_object ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_ac" UNIQUE NULLS NOT DISTINCT ("mib_id", "agent_capabilities_id", "agent_capabilities_module_id", "agent_capabilities_module_notification_id", "agent_capabilities_module_object_id");

ALTER TABLE public.mib_to_choice
  ADD CONSTRAINT "mib_to_choice_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_choice_choice_id_fkey" FOREIGN KEY ("choice_id") REFERENCES public.choice ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_c" UNIQUE NULLS NOT DISTINCT ("mib_id", "choice_id");

ALTER TABLE public.mib_to_explicit
  ADD CONSTRAINT "mib_to_explicit_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_explicit_explicit_id_fkey" FOREIGN KEY ("explicit_id") REFERENCES public.explicit ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_et" UNIQUE NULLS NOT DISTINCT ("mib_id", "explicit_id");

ALTER TABLE public.mib_to_implicit
  ADD CONSTRAINT "mib_to_implicit_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_implicit_implicit_id_fkey" FOREIGN KEY ("implicit_id") REFERENCES public.implicit ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_it" UNIQUE NULLS NOT DISTINCT ("mib_id", "implicit_id");

ALTER TABLE public.mib_to_import
  ADD CONSTRAINT "mib_to_import_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_import_import_id_fkey" FOREIGN KEY ("import_id") REFERENCES public.import ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_imp" UNIQUE NULLS NOT DISTINCT ("mib_id", "import_id");

ALTER TABLE public.mib_to_module_compliance
  ADD CONSTRAINT "mib_to_module_compliance_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_id_fkey" FOREIGN KEY ("module_compliance_id") REFERENCES public.module_compliance ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_module_id_fkey" FOREIGN KEY ("module_compliance_module_id") REFERENCES public.module_compliance_module ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_module_group_id_fkey" FOREIGN KEY ("module_compliance_module_group_id") REFERENCES public.module_compliance_module_group ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_module_object_id_fkey" FOREIGN KEY ("module_compliance_module_object_id") REFERENCES public.module_compliance_module_object ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_mc" UNIQUE NULLS NOT DISTINCT ("mib_id", "module_compliance_id", "module_compliance_module_id", "module_compliance_module_group_id", "module_compliance_module_object_id");

ALTER TABLE public.mib_to_module_identity
  ADD CONSTRAINT "mib_to_module_identity_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_identity_module_identity_id_fkey" FOREIGN KEY ("module_identity_id") REFERENCES public.module_identity ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_identity_revision_id_fkey" FOREIGN KEY ("revision_id") REFERENCES public.revision ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_mi_rev" UNIQUE NULLS NOT DISTINCT ("mib_id", "module_identity_id", "revision_id");

ALTER TABLE public.mib_to_notification_group
  ADD CONSTRAINT "mib_to_notification_group_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_notification_group_notification_group_id_fkey" FOREIGN KEY ("notification_group_id") REFERENCES public.notification_group ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_ng" UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_group_id");

ALTER TABLE public.mib_to_notification_type
  ADD CONSTRAINT "mib_to_notification_type_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_notification_type_notification_type_id_fkey" FOREIGN KEY ("notification_type_id") REFERENCES public.notification_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_nt" UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_type_id");

ALTER TABLE public.mib_to_object_group
  ADD CONSTRAINT "mib_to_object_group_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_group_object_group_id_fkey" FOREIGN KEY ("object_group_id") REFERENCES public.object_group ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_og" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_group_id");

ALTER TABLE public.mib_to_object_identifier
  ADD CONSTRAINT "mib_to_object_identifier_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_identifier_object_identifier_id_fkey" FOREIGN KEY ("object_identifier_id") REFERENCES public.object_identifier ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_oif" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identifier_id");

ALTER TABLE public.mib_to_object_identity
  ADD CONSTRAINT "mib_to_object_identity_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_identity_object_identity_id_fkey" FOREIGN KEY ("object_identity_id") REFERENCES public.object_identity ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_oit" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identity_id");

ALTER TABLE public.mib_to_object_type
  ADD CONSTRAINT "mib_to_object_type_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_type_object_type_id_fkey" FOREIGN KEY ("object_type_id") REFERENCES public.object_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_ot" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_type_id");

ALTER TABLE public.mib_to_sequence
  ADD CONSTRAINT "mib_to_sequence_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_sequence_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES public.sequence ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_sec" UNIQUE NULLS NOT DISTINCT ("mib_id", "sequence_id");

ALTER TABLE public.mib_to_textual_convention
  ADD CONSTRAINT "mib_to_textual_convention_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_textual_convention_textual_convention_id_fkey" FOREIGN KEY ("textual_convention_id") REFERENCES public.textual_convention ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_tc" UNIQUE NULLS NOT DISTINCT ("mib_id", "textual_convention_id");

ALTER TABLE public.mib_to_trap_type
  ADD CONSTRAINT "mib_to_trap_type_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_trap_type_trap_type_id_fkey" FOREIGN KEY ("trap_type_id") REFERENCES public.trap_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_tt" UNIQUE NULLS NOT DISTINCT ("mib_id", "trap_type_id");

ALTER TABLE public.oid
  ADD CONSTRAINT "oid_mib_fkey" FOREIGN KEY ("mib") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "oid_type_fkey" FOREIGN KEY ("type") REFERENCES public.asn1_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "oid_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "oid_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.component
  ADD CONSTRAINT "component_base_component_fkey" FOREIGN KEY ("base_component") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "component_access_fkey" FOREIGN KEY ("access") REFERENCES public.access ("id") ON DELETE CASCADE;

ALTER TABLE public.param
  ADD CONSTRAINT "param_type_fkey" FOREIGN KEY ("type") REFERENCES public.var_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "param_access_fkey" FOREIGN KEY ("access") REFERENCES public.access ("id") ON DELETE CASCADE;

ALTER TABLE public.component_param
  ADD CONSTRAINT "component_param_component_id_fkey" FOREIGN KEY ("component_id") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "component_param_param_id_fkey" FOREIGN KEY ("param_id") REFERENCES public.param ("id") ON DELETE CASCADE;

ALTER TABLE public.device_indicator
  ADD CONSTRAINT "device_indicator_tt" UNIQUE NULLS NOT DISTINCT ("description", "object_id", "contact", "name", "location", "services");

ALTER TABLE public.param_indicator
  ADD CONSTRAINT "param_indicator_oid_id_fkey" FOREIGN KEY ("oid_id") REFERENCES public.oid ("id") ON DELETE CASCADE;

ALTER TABLE public.mapping
  ADD CONSTRAINT "mapping_indicator_fkey" FOREIGN KEY ("indicator") REFERENCES public.param_indicator ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_param_fkey" FOREIGN KEY ("param") REFERENCES public.param ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_frequency_fkey" FOREIGN KEY ("frequency") REFERENCES public.polling_frequency ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_from_fkey" FOREIGN KEY ("from") REFERENCES public.mapping ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_position_type_fkey" FOREIGN KEY ("position_type") REFERENCES public.oid_type ("id") ON DELETE CASCADE;

ALTER TABLE public.device_component
  ADD CONSTRAINT "device_component_model_fkey" FOREIGN KEY ("model") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_component_parent_fkey" FOREIGN KEY ("parent") REFERENCES public.device_component ("id") ON DELETE CASCADE;

ALTER TABLE public.device_component_mapping
  ADD CONSTRAINT "device_component_mapping_device_component_id_fkey" FOREIGN KEY ("device_component_id") REFERENCES public.device_component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_component_mapping_mapping_id_fkey" FOREIGN KEY ("mapping_id") REFERENCES public.mapping ("id") ON DELETE CASCADE;

ALTER TABLE public.configuration
  ADD CONSTRAINT "configuration_indicator_fkey" FOREIGN KEY ("indicator") REFERENCES public.device_indicator ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "configuration_device_component_id_fkey" FOREIGN KEY ("device_component_id") REFERENCES public.device_component ("id") ON DELETE CASCADE;

ALTER TABLE public.default_configuration
  ADD CONSTRAINT "default_configuration_indicator_fkey" FOREIGN KEY ("indicator") REFERENCES public.device_indicator ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "default_configuration_device_component_id_fkey" FOREIGN KEY ("device_component_id") REFERENCES public.device_component ("id") ON DELETE CASCADE;

ALTER TABLE public.device_snmp
  ADD CONSTRAINT "device_snmp_version_fkey" FOREIGN KEY ("version") REFERENCES public.version_snmp ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_snmp_authentication_fkey" FOREIGN KEY ("authentication") REFERENCES public.auth_protocol_snmp ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_snmp_privacy_fkey" FOREIGN KEY ("privacy") REFERENCES public.privacy_protocol_snmp ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_snmp_config_fkey" FOREIGN KEY ("config") REFERENCES public.configuration ("id") ON DELETE CASCADE;

ALTER TABLE public.result
  ADD CONSTRAINT "result_component_fkey" FOREIGN KEY ("component") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "result_param_fkey" FOREIGN KEY ("param") REFERENCES public.param ("id") ON DELETE CASCADE;

ALTER TABLE public.affected_threshold
  ADD CONSTRAINT "affected_threshold_threshold_fkey" FOREIGN KEY ("threshold") REFERENCES public.threshold ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "affected_threshold_host_port_fkey" FOREIGN KEY ("host", "port") REFERENCES public.device_snmp ("host", "port") ON DELETE CASCADE;

ALTER TABLE public.affected_param
  ADD CONSTRAINT "affected_param_component_fkey" FOREIGN KEY ("component") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "affected_param_param_fkey" FOREIGN KEY ("param") REFERENCES public.param ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "affected_param_host_port_fkey" FOREIGN KEY ("host", "port") REFERENCES public.device_snmp ("host", "port") ON DELETE CASCADE;

ALTER TABLE public.config_in_process
  ADD CONSTRAINT "config_in_process_protocol_fkey" FOREIGN KEY ("protocol") REFERENCES public.polling_protocol ("id") ON DELETE CASCADE;