package service

var tableSchemas = map[string]string{
	"public.polling_protocol": `CREATE TABLE IF NOT EXISTS public.polling_protocol (
								    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "value" VARCHAR(10)
								);`,
	"public.access": `CREATE TABLE IF NOT EXISTS public.access (
					      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "value" VARCHAR(5)
					  );`,
	"public.version_snmp": `CREATE TABLE IF NOT EXISTS public.version_snmp (
							    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							    "value" VARCHAR(3)
							);`,
	"public.auth_protocol_snmp": `CREATE TABLE IF NOT EXISTS public.auth_protocol_snmp (
								      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "value" VARCHAR(10)
								  );`,
	"public.privacy_protocol_snmp": `CREATE TABLE IF NOT EXISTS public.privacy_protocol_snmp (
									     "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									     "value" VARCHAR(10)
									 );`,
	"public.oid_type": `CREATE TABLE IF NOT EXISTS public.oid_type (
						    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "value" VARCHAR(17)
						);`,
	"public.logic_operator": `CREATE TABLE IF NOT EXISTS public.logic_operator (
							      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							      "value" VARCHAR(12) NOT NULL UNIQUE,
							      "type" VARCHAR(15) NOT NULL,
							      "precedence" SMALLINT NOT NULL,
							      "arity" SMALLINT NOT NULL
							  );`,
	"public.alarm_level": `CREATE TABLE IF NOT EXISTS public.alarm_level (
						       "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						       "value" VARCHAR(12)
						   );`,
	"public.var_type": `CREATE TABLE IF NOT EXISTS public.var_type (
						    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "value" VARCHAR(17)
						);`,
	"public.polling_frequency": `CREATE TABLE IF NOT EXISTS public.polling_frequency (
								     "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "value" VARCHAR(6)
								 );`,
	"public.oid_access": `CREATE TABLE IF NOT EXISTS public.oid_access (
						      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						      "value" VARCHAR(21) UNIQUE NOT NULL
						  );`,
	"public.oid_status": `CREATE TABLE IF NOT EXISTS public.oid_status (
						      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						      "value" VARCHAR(10) UNIQUE NOT NULL
						  );`,
	"public.asn1_type": `CREATE TABLE IF NOT EXISTS public.asn1_type (
						     "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "value" VARCHAR(18) UNIQUE NOT NULL
						 );`,
	"public.vendor": `CREATE TABLE IF NOT EXISTS public.vendor (
					      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "name" VARCHAR(255) NOT NULL,
					      "number" INTEGER UNIQUE NOT NULL,
					      "contact" TEXT,
					      "email" TEXT,
					      "directory" VARCHAR(255)
					  );`,
	"public.component": `CREATE TABLE IF NOT EXISTS public.component (
						     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "title" VARCHAR NOT NULL,
						     "name_en" VARCHAR NOT NULL,
						     "name_ru" VARCHAR NOT NULL,
						     "plural_name_en" VARCHAR NOT NULL,
						     "plural_name_ru" VARCHAR NOT NULL,
						     "base_component" BIGINT,
						     "description_en" TEXT,
						     "description_ru" TEXT,
						     "access" SMALLINT NOT NULL
						 );`,
	"public.param": `CREATE TABLE IF NOT EXISTS public.param (
					     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					     "title" VARCHAR NOT NULL,
					     "name_en" VARCHAR NOT NULL,
					     "name_ru" VARCHAR NOT NULL,
					     "type" SMALLINT NOT NULL,
					     "value" TEXT,
					     "description_en" TEXT,
					     "description_ru" TEXT,
					     "units_en" TEXT,
					     "units_ru" TEXT,
					     "access" SMALLINT NOT NULL,
					     "saved" BOOLEAN NOT NULL,
					     "visible" BOOLEAN NOT NULL
					 );`,
	"public.component_param": `CREATE TABLE IF NOT EXISTS public.component_param (
							       "component_id" BIGINT NOT NULL,
							       "param_id" BIGINT NOT NULL,
							       PRIMARY KEY ("component_id", "param_id")
							   );`,
	"public.agent_capabilities": `CREATE TABLE IF NOT EXISTS public.agent_capabilities (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "name" VARCHAR(255) NOT NULL,
								      "product_release" TEXT,
								      "status" SMALLINT,
								      "description" TEXT,
								      "reference" TEXT
								  );`,
	"public.agent_capabilities_module": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "supports" VARCHAR(255),
										     "includes" VARCHAR(255)[]
										 );`,
	"public.agent_capabilities_module_notification": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_notification (
													      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
													      "variation" VARCHAR(255),
													      "access" SMALLINT,
													      "description" TEXT
													  );`,
	"public.agent_capabilities_module_object": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_object (
												    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
												    "variation" VARCHAR(255),
												    "syntax" VARCHAR(255),
												    "write_syntax" VARCHAR(255),
												    "access" SMALLINT,
												    "creation_requires" VARCHAR(255)[],
												    "defval" VARCHAR(255),
												    "description" TEXT
												);`,
	"public.choice": `CREATE TABLE IF NOT EXISTS public.choice (
					      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "name" VARCHAR(255) NOT NULL,
					      "choices" JSONB NOT NULL
					  );`,
	"public.explicit": `CREATE TABLE IF NOT EXISTS public.explicit (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "name" VARCHAR(255) NOT NULL,
						    "value" TEXT NOT NULL
						);`,
	"public.implicit": `CREATE TABLE IF NOT EXISTS public.implicit (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "name" VARCHAR(255) NOT NULL,
						    "application" SMALLINT NOT NULL,
						    "value" VARCHAR(255) NOT NULL
						);`,
	"public.import": `CREATE TABLE IF NOT EXISTS public.import (
					      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "param" VARCHAR(255) NOT NULL,
					      "from" VARCHAR(255) NOT NULL
					  );`,
	"public.mib": `CREATE TABLE IF NOT EXISTS public.mib (
				       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				       "path" TEXT UNIQUE NOT NULL,
				       "name" VARCHAR(50),
				       "vendor" BIGINT
				   );`,
	"public.module_compliance": `CREATE TABLE IF NOT EXISTS public.module_compliance (
								     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "name" VARCHAR(255) NOT NULL,
								     "status" SMALLINT,
								     "description" TEXT,
								     "reference" TEXT
								 );`,
	"public.module_compliance_module": `CREATE TABLE IF NOT EXISTS public.module_compliance_module (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "name" VARCHAR(255) NOT NULL,
										    "mandatory_groups" VARCHAR(255)[]
										);`,
	"public.module_compliance_module_group": `CREATE TABLE IF NOT EXISTS public.module_compliance_module_group (
											      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
											      "name" VARCHAR(255) NOT NULL,
											      "description" TEXT
											  );`,
	"public.module_compliance_module_object": `CREATE TABLE IF NOT EXISTS public.module_compliance_module_object (
											       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
											       "name" VARCHAR(255) NOT NULL,
											       "syntax" VARCHAR(255),
											       "write_syntax" VARCHAR(255),
											       "access" SMALLINT,
											       "description" TEXT
											   );`,
	"public.module_identity": `CREATE TABLE IF NOT EXISTS public.module_identity (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "name" VARCHAR(255) NOT NULL,
							       "last_updated" TIMESTAMP,
							       "organization" VARCHAR(255),
							       "contact_info" TEXT,
							       "description"  TEXT
							   );`,
	"public.notification_group": `CREATE TABLE IF NOT EXISTS public.notification_group (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "name" VARCHAR(255) NOT NULL,
								      "notifications" VARCHAR(255)[],
								      "status" SMALLINT,
								      "description" TEXT,
								      "reference" TEXT
								  );`,
	"public.notification_type": `CREATE TABLE IF NOT EXISTS public.notification_type (
								     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "name" VARCHAR(255) NOT NULL,
								     "objects" VARCHAR(255)[],
								     "status" SMALLINT,
								     "description" TEXT,
								     "reference" TEXT
								 );`,
	"public.object_group": `CREATE TABLE IF NOT EXISTS public.object_group (
							    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							    "name" VARCHAR(255) NOT NULL,
							    "objects" VARCHAR[],
							    "status" SMALLINT,
							    "description" TEXT,
							    "reference" TEXT
							);`,
	"public.object_identifier": `CREATE TABLE IF NOT EXISTS public.object_identifier (
								     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "name" VARCHAR(255) NOT NULL,
								     "num_oid" VARCHAR[],
								     "str_oid" VARCHAR[],
								     "parent" VARCHAR(255),
								     "type" SMALLINT NOT NULL
								 );`,
	"public.object_identity": `CREATE TABLE IF NOT EXISTS public.object_identity (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "name" VARCHAR(255) NOT NULL,
							       "status" SMALLINT,
							       "description" TEXT,
							       "reference" TEXT
							   );`,
	"public.object_type": `CREATE TABLE IF NOT EXISTS public.object_type (
						       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						       "name" VARCHAR(255) NOT NULL,
						       "syntax" TEXT,
						       "units" VARCHAR(255),
						       "access" SMALLINT,
						       "status" SMALLINT,
						       "description" TEXT,
						       "reference" TEXT,
						       "index" VARCHAR(255)[],
						       "augments" VARCHAR(255)[],
						       "default_value" VARCHAR(255)
						   );`,
	"public.oid": `CREATE TABLE IF NOT EXISTS public.oid (
				       "id" UUID PRIMARY KEY,
				       "mib" BIGINT,
				       "type" SMALLINT NOT NULL,
				       "name" VARCHAR(255) NOT NULL,
				       "number" INTEGER,
				       "dotter_notation" TEXT NOT NULL,
				       "object_descriptor" TEXT NOT NULL,
				       "syntax" TEXT,
				       "enum" JSONB,
				       "status" SMALLINT,
				       "access" SMALLINT,
				       "units" VARCHAR(255),
				       "description" TEXT,
				       "category" VARCHAR(255)
				   );`,
	"public.revision": `CREATE TABLE IF NOT EXISTS public.revision (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "revision" TIMESTAMP,
						    "description" TEXT
						);`,
	"public.sequence": `CREATE TABLE IF NOT EXISTS public.sequence (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "name" VARCHAR(255) NOT NULL,
						    "pairs" JSONB NOT NULL
						);`,
	"public.textual_convention": `CREATE TABLE IF NOT EXISTS public.textual_convention (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "name" VARCHAR(255) NOT NULL,
								      "display_hint" VARCHAR(255),
								      "status" SMALLINT,
								      "description" TEXT,
								      "reference" TEXT,
								      "syntax" TEXT
								  );`,
	"public.trap_type": `CREATE TABLE IF NOT EXISTS public.trap_type (
						     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "name" VARCHAR(255) NOT NULL,
						     "variables" VARCHAR(255)[],
						     "description" TEXT,
						     "reference" TEXT
						 );`,
	"public.mib_to_agent_capabilities": `CREATE TABLE IF NOT EXISTS public.mib_to_agent_capabilities (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "mib_id" BIGINT NOT NULL,
										     "agent_capabilities_id" BIGINT NOT NULL,
										     "agent_capabilities_module_id" BIGINT,
										     "agent_capabilities_module_notification_id" BIGINT,
										     "agent_capabilities_module_object_id" BIGINT,
										     CONSTRAINT mib_ac UNIQUE NULLS NOT DISTINCT ("mib_id", "agent_capabilities_id", "agent_capabilities_module_id", "agent_capabilities_module_notification_id", "agent_capabilities_module_object_id")
										 );`,
	"public.mib_to_choice": `CREATE TABLE IF NOT EXISTS public.mib_to_choice (
							     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							     "mib_id" BIGINT NOT NULL,
							     "choice_id" BIGINT NOT NULL,
							     CONSTRAINT mib_c UNIQUE NULLS NOT DISTINCT ("mib_id", "choice_id")
							 );`,
	"public.mib_to_explicit": `CREATE TABLE IF NOT EXISTS public.mib_to_explicit (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "mib_id" BIGINT NOT NULL,
							       "explicit_id" BIGINT NOT NULL,
							       CONSTRAINT mib_et UNIQUE NULLS NOT DISTINCT ("mib_id", "explicit_id")
							   );`,
	"public.mib_to_implicit": `CREATE TABLE IF NOT EXISTS public.mib_to_implicit (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "mib_id" BIGINT NOT NULL,
							       "implicit_id" BIGINT NOT NULL,
							       CONSTRAINT mib_it UNIQUE NULLS NOT DISTINCT ("mib_id", "implicit_id")
							   );`,
	"public.mib_to_import": `CREATE TABLE IF NOT EXISTS public.mib_to_import (
							     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							     "mib_id" BIGINT NOT NULL,
							     "import_id" BIGINT NOT NULL,
							     CONSTRAINT mib_imp UNIQUE NULLS NOT DISTINCT ("mib_id", "import_id")
							 );`,
	"public.mib_to_module_compliance": `CREATE TABLE IF NOT EXISTS public.mib_to_module_compliance (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "mib_id" BIGINT NOT NULL,
										    "module_compliance_id" BIGINT NOT NULL,
										    "module_compliance_module_id" BIGINT,
										    "module_compliance_module_group_id" BIGINT,
										    "module_compliance_module_object_id" BIGINT,
										    CONSTRAINT mib_mc UNIQUE NULLS NOT DISTINCT ("mib_id", "module_compliance_id", "module_compliance_module_id", "module_compliance_module_group_id", "module_compliance_module_object_id")
										);`,
	"public.mib_to_module_identity": `CREATE TABLE IF NOT EXISTS public.mib_to_module_identity (
									      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									      "mib_id" BIGINT NOT NULL,
									      "module_identity_id" BIGINT NOT NULL,
									      "revision_id" BIGINT,
									      CONSTRAINT mib_mi_rev UNIQUE NULLS NOT DISTINCT ("mib_id", "module_identity_id", "revision_id")
									  );`,
	"public.mib_to_notification_group": `CREATE TABLE IF NOT EXISTS public.mib_to_notification_group (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "mib_id" BIGINT NOT NULL,
										     "notification_group_id" BIGINT NOT NULL,
										     CONSTRAINT mib_ng UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_group_id")
										 );`,
	"public.mib_to_notification_type": `CREATE TABLE IF NOT EXISTS public.mib_to_notification_type (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "mib_id" BIGINT NOT NULL,
										    "notification_type_id" BIGINT NOT NULL,
										    CONSTRAINT mib_nt UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_type_id")
										);`,
	"public.mib_to_object_group": `CREATE TABLE IF NOT EXISTS public.mib_to_object_group (
								       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								       "mib_id" BIGINT NOT NULL,
								       "object_group_id" BIGINT NOT NULL,
								       CONSTRAINT mib_og UNIQUE NULLS NOT DISTINCT ("mib_id", "object_group_id")
								   );`,
	"public.mib_to_object_identifier": `CREATE TABLE IF NOT EXISTS public.mib_to_object_identifier (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "mib_id" BIGINT NOT NULL,
										    "object_identifier_id" BIGINT NOT NULL,
										    CONSTRAINT mib_oif UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identifier_id")
										);`,
	"public.mib_to_object_identity": `CREATE TABLE IF NOT EXISTS public.mib_to_object_identity (
									      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									      "mib_id" BIGINT NOT NULL,
									      "object_identity_id" BIGINT NOT NULL,
									      CONSTRAINT mib_oit UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identity_id")
									  );`,
	"public.mib_to_object_type": `CREATE TABLE IF NOT EXISTS public.mib_to_object_type (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "mib_id" BIGINT NOT NULL,
								      "object_type_id" BIGINT NOT NULL,
								      CONSTRAINT mib_ot UNIQUE NULLS NOT DISTINCT ("mib_id", "object_type_id")
								  );`,
	"public.mib_to_sequence": `CREATE TABLE IF NOT EXISTS public.mib_to_sequence (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "mib_id" BIGINT NOT NULL,
							       "sequence_id" BIGINT NOT NULL,
							       CONSTRAINT mib_sec UNIQUE NULLS NOT DISTINCT ("mib_id", "sequence_id")
							   );`,
	"public.mib_to_textual_convention": `CREATE TABLE IF NOT EXISTS public.mib_to_textual_convention (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "mib_id" BIGINT NOT NULL,
										     "textual_convention_id" BIGINT NOT NULL,
										     CONSTRAINT mib_tc UNIQUE NULLS NOT DISTINCT ("mib_id", "textual_convention_id")
										 );`,
	"public.mib_to_trap_type": `CREATE TABLE IF NOT EXISTS public.mib_to_trap_type (
								    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "mib_id" BIGINT NOT NULL,
								    "trap_type_id" BIGINT NOT NULL,
								    CONSTRAINT mib_tt UNIQUE NULLS NOT DISTINCT ("mib_id", "trap_type_id")
								);`,
	"public.device_indicator": `CREATE TABLE IF NOT EXISTS public.device_indicator (
								    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "description" TEXT,
								    "object_id" TEXT NOT NULL,
								    "contact" TEXT,
								    "name" TEXT,
								    "location" TEXT,
								    "services" SMALLINT,
								    CONSTRAINT device_indicator_tt UNIQUE NULLS NOT DISTINCT ("description", "object_id", "contact", "name", "location", "services")
								);`,
	"public.param_indicator": `CREATE TABLE IF NOT EXISTS public.param_indicator (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "oid_id" UUID,
							       "dotter_notation" TEXT
							   );`,
	"public.mapping": `CREATE TABLE IF NOT EXISTS public.mapping (
					       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					       "indicator" BIGINT NOT NULL,
					       "param" BIGINT NOT NULL,
					       "frequency" SMALLINT NOT NULL,
					       "value" VARCHAR(255),
					       "coefficient" NUMERIC(38, 12),
					       "enum" JSONB,
					       "position" SMALLINT,
					       "from" BIGINT,
					       "position_type" SMALLINT
					   );`,
	"public.device_component": `CREATE TABLE IF NOT EXISTS public.device_component (
								    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "model" BIGINT NOT NULL,
								    "internal_order" INTEGER DEFAULT 1,
								    "parent" BIGINT
								);`,
	"public.device_component_mapping": `CREATE TABLE IF NOT EXISTS public.device_component_mapping (
										    "device_component_id" BIGINT NOT NULL,
										    "mapping_id" BIGINT NOT NULL,
										    PRIMARY KEY ("device_component_id", "mapping_id")
										);`,
	"public.configuration": `CREATE TABLE IF NOT EXISTS public.configuration (
							     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							     "indicator" BIGINT NOT NULL,
							     "device_component_id" BIGINT
							 );`,
	"public.default_configuration": `CREATE TABLE IF NOT EXISTS public.default_configuration (
									     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									     "indicator" BIGINT NOT NULL,
									     "device_component_id" BIGINT
									 );`,
	"public.threshold": `CREATE TABLE IF NOT EXISTS public.threshold (
						     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "name" VARCHAR(255) NOT NULL,
						     "description" TEXT,
						     "author" VARCHAR(255),
						     "created" TIMESTAMP,
						     "query" TEXT UNIQUE NOT NULL
						 );`,
	"public.device_snmp": `CREATE TABLE IF NOT EXISTS public.device_snmp (
						       "host" VARCHAR(30) NOT NULL,
						       "port" INTEGER NOT NULL,
						       "community" VARCHAR(255) NOT NULL,
						       "version" SMALLINT NOT NULL,
						       "login" VARCHAR(255),
						       "password" TEXT,
						       "authentication" SMALLINT NOT NULL,
						       "privacy" SMALLINT NOT NULL,
						       "id" UUID UNIQUE NOT NULL,
						       "config" BIGINT,
						       PRIMARY KEY ("host", "port")
						   );`,
	"public.result": `CREATE TABLE IF NOT EXISTS public.result (
					      "host" VARCHAR(30) NOT NULL,
					      "port" INTEGER NOT NULL,
					      "component" BIGINT NOT NULL,
					      "internal_order" INTEGER DEFAULT 1,
					      "param" BIGINT NOT NULL,
					      "value" TEXT,
					      PRIMARY KEY ("host", "port", "component", "internal_order", "param")
					  );`,
	"public.affected_threshold": `CREATE TABLE IF NOT EXISTS public.affected_threshold (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "host" VARCHAR(30) NOT NULL,
								      "port" INTEGER NOT NULL,
								      "threshold" BIGINT NOT NULL,
								      "enabled" BOOLEAN DEFAULT true
								  );`,
	"public.affected_param": `CREATE TABLE IF NOT EXISTS public.affected_param (
							      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							      "host" VARCHAR(30) NOT NULL,
							      "port" INTEGER NOT NULL,
							      "component" BIGINT NOT NULL,
							      "internal_order" INTEGER DEFAULT 1,
							      "param" BIGINT NOT NULL
							  );`,
	"public.config_in_process": `CREATE TABLE IF NOT EXISTS public.config_in_process (
								     "host" VARCHAR(255) NOT NULL,
								     "port" INTEGER NOT NULL,
								     "protocol" SMALLINT NOT NULL,
								     PRIMARY KEY ("host", "port", "protocol")
								 );`,
}
