package service

import (
	"configurator/internal/dao"
	"configurator/internal/logger"
	"context"
	"fmt"
	"sort"
	"sync"
)

var tableSchemas = map[string]string{
	"public.polling_protocol": `CREATE TABLE IF NOT EXISTS public.polling_protocol (
								    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "value" VARCHAR(10)
								);`,
	"public.access": `CREATE TABLE IF NOT EXISTS public.access (
					      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "value" VARCHAR(5)
					  );`,
	"public.version_snmp": `CREATE TABLE IF NOT EXISTS public.version_snmp (
							    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							    "value" VARCHAR(3)
							);`,
	"public.auth_protocol_snmp": `CREATE TABLE IF NOT EXISTS public.auth_protocol_snmp (
								      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "value" VARCHAR(10)
								  );`,
	"public.privacy_protocol_snmp": `CREATE TABLE IF NOT EXISTS public.privacy_protocol_snmp (
									     "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									     "value" VARCHAR(10)
									 );`,
	"public.oid_type": `CREATE TABLE IF NOT EXISTS public.oid_type (
						    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "value" VARCHAR(17)
						);`,
	"public.logic_operator": `CREATE TABLE IF NOT EXISTS public.logic_operator (
							      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							      "value" VARCHAR(12) NOT NULL UNIQUE,
							      "type" VARCHAR(15) NOT NULL,
							      "precedence" SMALLINT NOT NULL,
							      "arity" SMALLINT NOT NULL
							  );`,
	"public.alarm_level": `CREATE TABLE IF NOT EXISTS public.alarm_level (
						       "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						       "value" VARCHAR(12)
						   );`,
	"public.var_type": `CREATE TABLE IF NOT EXISTS public.var_type (
						    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "value" VARCHAR(17)
						);`,
	"public.polling_frequency": `CREATE TABLE IF NOT EXISTS public.polling_frequency (
								     "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "value" VARCHAR(6)
								 );`,
	"public.oid_access": `CREATE TABLE IF NOT EXISTS public.oid_access (
						      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						      "value" VARCHAR(21) UNIQUE NOT NULL
						  );`,
	"public.oid_status": `CREATE TABLE IF NOT EXISTS public.oid_status (
						      "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						      "value" VARCHAR(10) UNIQUE NOT NULL
						  );`,
	"public.asn1_type": `CREATE TABLE IF NOT EXISTS public.asn1_type (
						     "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "value" VARCHAR(18) UNIQUE NOT NULL
						 );`,
	"public.vendor": `CREATE TABLE IF NOT EXISTS public.vendor (
					      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "name" VARCHAR(255) NOT NULL,
					      "number" INTEGER UNIQUE NOT NULL,
					      "contact" TEXT,
					      "email" TEXT,
					      "directory" VARCHAR(255)
					  );`,
	"public.component": `CREATE TABLE IF NOT EXISTS public.component (
						     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "title" VARCHAR NOT NULL,
						     "name_en" VARCHAR NOT NULL,
						     "name_ru" VARCHAR NOT NULL,
						     "plural_name_en" VARCHAR NOT NULL,
						     "plural_name_ru" VARCHAR NOT NULL,
						     "base_component" BIGINT,
						     "description_en" TEXT,
						     "description_ru" TEXT,
						     "access" SMALLINT NOT NULL
						 );`,
	"public.param": `CREATE TABLE IF NOT EXISTS public.param (
					     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					     "title" VARCHAR NOT NULL,
					     "name_en" VARCHAR NOT NULL,
					     "name_ru" VARCHAR NOT NULL,
					     "type" SMALLINT NOT NULL,
					     "value" TEXT,
					     "description_en" TEXT,
					     "description_ru" TEXT,
					     "units_en" TEXT,
					     "units_ru" TEXT,
					     "access" SMALLINT NOT NULL,
					     "saved" BOOLEAN NOT NULL,
					     "visible" BOOLEAN NOT NULL
					 );`,
	"public.component_param": `CREATE TABLE IF NOT EXISTS public.component_param (
							       "component_id" BIGINT NOT NULL,
							       "param_id" BIGINT NOT NULL,
							       PRIMARY KEY ("component_id", "param_id")
							   );`,
	"public.agent_capabilities": `CREATE TABLE IF NOT EXISTS public.agent_capabilities (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "name" VARCHAR(255) NOT NULL,
								      "product_release" TEXT,
								      "status" SMALLINT,
								      "description" TEXT,
								      "reference" TEXT
								  );`,
	"public.agent_capabilities_module": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "supports" VARCHAR(255),
										     "includes" VARCHAR(255)[]
										 );`,
	"public.agent_capabilities_module_notification": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_notification (
													      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
													      "variation" VARCHAR(255),
													      "access" SMALLINT,
													      "description" TEXT
													  );`,
	"public.agent_capabilities_module_object": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_object (
												    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
												    "variation" VARCHAR(255),
												    "syntax" VARCHAR(255),
												    "write_syntax" VARCHAR(255),
												    "access" SMALLINT,
												    "creation_requires" VARCHAR(255)[],
												    "defval" VARCHAR(255),
												    "description" TEXT
												);`,
	"public.choice": `CREATE TABLE IF NOT EXISTS public.choice (
					      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "name" VARCHAR(255) NOT NULL,
					      "choices" JSONB NOT NULL
					  );`,
	"public.explicit": `CREATE TABLE IF NOT EXISTS public.explicit (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "name" VARCHAR(255) NOT NULL,
						    "value" TEXT NOT NULL
						);`,
	"public.implicit": `CREATE TABLE IF NOT EXISTS public.implicit (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "name" VARCHAR(255) NOT NULL,
						    "application" SMALLINT NOT NULL,
						    "value" VARCHAR(255) NOT NULL
						);`,
	"public.import": `CREATE TABLE IF NOT EXISTS public.import (
					      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					      "param" VARCHAR(255) NOT NULL,
					      "from" VARCHAR(255) NOT NULL
					  );`,
	"public.mib": `CREATE TABLE IF NOT EXISTS public.mib (
				       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				       "path" TEXT UNIQUE NOT NULL,
				       "name" VARCHAR(50),
				       "vendor" BIGINT
				   );`,
	"public.module_compliance": `CREATE TABLE IF NOT EXISTS public.module_compliance (
								     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "name" VARCHAR(255) NOT NULL,
								     "status" SMALLINT,
								     "description" TEXT,
								     "reference" TEXT
								 );`,
	"public.module_compliance_module": `CREATE TABLE IF NOT EXISTS public.module_compliance_module (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "name" VARCHAR(255) NOT NULL,
										    "mandatory_groups" VARCHAR(255)[]
										);`,
	"public.module_compliance_module_group": `CREATE TABLE IF NOT EXISTS public.module_compliance_module_group (
											      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
											      "name" VARCHAR(255) NOT NULL,
											      "description" TEXT
											  );`,
	"public.module_compliance_module_object": `CREATE TABLE IF NOT EXISTS public.module_compliance_module_object (
											       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
											       "name" VARCHAR(255) NOT NULL,
											       "syntax" VARCHAR(255),
											       "write_syntax" VARCHAR(255),
											       "access" SMALLINT,
											       "description" TEXT
											   );`,
	"public.module_identity": `CREATE TABLE IF NOT EXISTS public.module_identity (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "name" VARCHAR(255) NOT NULL,
							       "last_updated" TIMESTAMP,
							       "organization" VARCHAR(255),
							       "contact_info" TEXT,
							       "description"  TEXT
							   );`,
	"public.notification_group": `CREATE TABLE IF NOT EXISTS public.notification_group (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "name" VARCHAR(255) NOT NULL,
								      "notifications" VARCHAR(255)[],
								      "status" SMALLINT,
								      "description" TEXT,
								      "reference" TEXT
								  );`,
	"public.notification_type": `CREATE TABLE IF NOT EXISTS public.notification_type (
								     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "name" VARCHAR(255) NOT NULL,
								     "objects" VARCHAR(255)[],
								     "status" SMALLINT,
								     "description" TEXT,
								     "reference" TEXT
								 );`,
	"public.object_group": `CREATE TABLE IF NOT EXISTS public.object_group (
							    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							    "name" VARCHAR(255) NOT NULL,
							    "objects" VARCHAR[],
							    "status" SMALLINT,
							    "description" TEXT,
							    "reference" TEXT
							);`,
	"public.object_identifier": `CREATE TABLE IF NOT EXISTS public.object_identifier (
								     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								     "name" VARCHAR(255) NOT NULL,
								     "num_oid" VARCHAR[],
								     "str_oid" VARCHAR[],
								     "parent" VARCHAR(255),
								     "type" SMALLINT NOT NULL
								 );`,
	"public.object_identity": `CREATE TABLE IF NOT EXISTS public.object_identity (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "name" VARCHAR(255) NOT NULL,
							       "status" SMALLINT,
							       "description" TEXT,
							       "reference" TEXT
							   );`,
	"public.object_type": `CREATE TABLE IF NOT EXISTS public.object_type (
						       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						       "name" VARCHAR(255) NOT NULL,
						       "syntax" TEXT,
						       "units" VARCHAR(255),
						       "access" SMALLINT,
						       "status" SMALLINT,
						       "description" TEXT,
						       "reference" TEXT,
						       "index" VARCHAR(255)[],
						       "augments" VARCHAR(255)[],
						       "default_value" VARCHAR(255)
						   );`,
	"public.oid": `CREATE TABLE IF NOT EXISTS public.oid (
				       "id" UUID PRIMARY KEY,
				       "mib" BIGINT,
				       "type" SMALLINT NOT NULL,
				       "name" VARCHAR(255) NOT NULL,
				       "number" INTEGER,
				       "dotter_notation" TEXT NOT NULL,
				       "object_descriptor" TEXT NOT NULL,
				       "syntax" TEXT,
				       "enum" JSONB,
				       "status" SMALLINT,
				       "access" SMALLINT,
				       "units" VARCHAR(255),
				       "description" TEXT,
				       "category" VARCHAR(255)
				   );`,
	"public.revision": `CREATE TABLE IF NOT EXISTS public.revision (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "revision" TIMESTAMP,
						    "description" TEXT
						);`,
	"public.sequence": `CREATE TABLE IF NOT EXISTS public.sequence (
						    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    "name" VARCHAR(255) NOT NULL,
						    "pairs" JSONB NOT NULL
						);`,
	"public.textual_convention": `CREATE TABLE IF NOT EXISTS public.textual_convention (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "name" VARCHAR(255) NOT NULL,
								      "display_hint" VARCHAR(255),
								      "status" SMALLINT,
								      "description" TEXT,
								      "reference" TEXT,
								      "syntax" TEXT
								  );`,
	"public.trap_type": `CREATE TABLE IF NOT EXISTS public.trap_type (
						     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "name" VARCHAR(255) NOT NULL,
						     "variables" VARCHAR(255)[],
						     "description" TEXT,
						     "reference" TEXT
						 );`,
	"public.mib_to_agent_capabilities": `CREATE TABLE IF NOT EXISTS public.mib_to_agent_capabilities (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "mib_id" BIGINT NOT NULL,
										     "agent_capabilities_id" BIGINT NOT NULL,
										     "agent_capabilities_module_id" BIGINT,
										     "agent_capabilities_module_notification_id" BIGINT,
										     "agent_capabilities_module_object_id" BIGINT,
										     CONSTRAINT mib_ac UNIQUE NULLS NOT DISTINCT ("mib_id", "agent_capabilities_id", "agent_capabilities_module_id", "agent_capabilities_module_notification_id", "agent_capabilities_module_object_id")
										 );`,
	"public.mib_to_choice": `CREATE TABLE IF NOT EXISTS public.mib_to_choice (
							     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							     "mib_id" BIGINT NOT NULL,
							     "choice_id" BIGINT NOT NULL,
							     CONSTRAINT mib_c UNIQUE NULLS NOT DISTINCT ("mib_id", "choice_id")
							 );`,
	"public.mib_to_explicit": `CREATE TABLE IF NOT EXISTS public.mib_to_explicit (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "mib_id" BIGINT NOT NULL,
							       "explicit_id" BIGINT NOT NULL,
							       CONSTRAINT mib_et UNIQUE NULLS NOT DISTINCT ("mib_id", "explicit_id")
							   );`,
	"public.mib_to_implicit": `CREATE TABLE IF NOT EXISTS public.mib_to_implicit (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "mib_id" BIGINT NOT NULL,
							       "implicit_id" BIGINT NOT NULL,
							       CONSTRAINT mib_it UNIQUE NULLS NOT DISTINCT ("mib_id", "implicit_id")
							   );`,
	"public.mib_to_import": `CREATE TABLE IF NOT EXISTS public.mib_to_import (
							     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							     "mib_id" BIGINT NOT NULL,
							     "import_id" BIGINT NOT NULL,
							     CONSTRAINT mib_imp UNIQUE NULLS NOT DISTINCT ("mib_id", "import_id")
							 );`,
	"public.mib_to_module_compliance": `CREATE TABLE IF NOT EXISTS public.mib_to_module_compliance (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "mib_id" BIGINT NOT NULL,
										    "module_compliance_id" BIGINT NOT NULL,
										    "module_compliance_module_id" BIGINT,
										    "module_compliance_module_group_id" BIGINT,
										    "module_compliance_module_object_id" BIGINT,
										    CONSTRAINT mib_mc UNIQUE NULLS NOT DISTINCT ("mib_id", "module_compliance_id", "module_compliance_module_id", "module_compliance_module_group_id", "module_compliance_module_object_id")
										);`,
	"public.mib_to_module_identity": `CREATE TABLE IF NOT EXISTS public.mib_to_module_identity (
									      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									      "mib_id" BIGINT NOT NULL,
									      "module_identity_id" BIGINT NOT NULL,
									      "revision_id" BIGINT,
									      CONSTRAINT mib_mi_rev UNIQUE NULLS NOT DISTINCT ("mib_id", "module_identity_id", "revision_id")
									  );`,
	"public.mib_to_notification_group": `CREATE TABLE IF NOT EXISTS public.mib_to_notification_group (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "mib_id" BIGINT NOT NULL,
										     "notification_group_id" BIGINT NOT NULL,
										     CONSTRAINT mib_ng UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_group_id")
										 );`,
	"public.mib_to_notification_type": `CREATE TABLE IF NOT EXISTS public.mib_to_notification_type (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "mib_id" BIGINT NOT NULL,
										    "notification_type_id" BIGINT NOT NULL,
										    CONSTRAINT mib_nt UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_type_id")
										);`,
	"public.mib_to_object_group": `CREATE TABLE IF NOT EXISTS public.mib_to_object_group (
								       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								       "mib_id" BIGINT NOT NULL,
								       "object_group_id" BIGINT NOT NULL,
								       CONSTRAINT mib_og UNIQUE NULLS NOT DISTINCT ("mib_id", "object_group_id")
								   );`,
	"public.mib_to_object_identifier": `CREATE TABLE IF NOT EXISTS public.mib_to_object_identifier (
										    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										    "mib_id" BIGINT NOT NULL,
										    "object_identifier_id" BIGINT NOT NULL,
										    CONSTRAINT mib_oif UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identifier_id")
										);`,
	"public.mib_to_object_identity": `CREATE TABLE IF NOT EXISTS public.mib_to_object_identity (
									      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									      "mib_id" BIGINT NOT NULL,
									      "object_identity_id" BIGINT NOT NULL,
									      CONSTRAINT mib_oit UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identity_id")
									  );`,
	"public.mib_to_object_type": `CREATE TABLE IF NOT EXISTS public.mib_to_object_type (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "mib_id" BIGINT NOT NULL,
								      "object_type_id" BIGINT NOT NULL,
								      CONSTRAINT mib_ot UNIQUE NULLS NOT DISTINCT ("mib_id", "object_type_id")
								  );`,
	"public.mib_to_sequence": `CREATE TABLE IF NOT EXISTS public.mib_to_sequence (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "mib_id" BIGINT NOT NULL,
							       "sequence_id" BIGINT NOT NULL,
							       CONSTRAINT mib_sec UNIQUE NULLS NOT DISTINCT ("mib_id", "sequence_id")
							   );`,
	"public.mib_to_textual_convention": `CREATE TABLE IF NOT EXISTS public.mib_to_textual_convention (
										     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										     "mib_id" BIGINT NOT NULL,
										     "textual_convention_id" BIGINT NOT NULL,
										     CONSTRAINT mib_tc UNIQUE NULLS NOT DISTINCT ("mib_id", "textual_convention_id")
										 );`,
	"public.mib_to_trap_type": `CREATE TABLE IF NOT EXISTS public.mib_to_trap_type (
								    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "mib_id" BIGINT NOT NULL,
								    "trap_type_id" BIGINT NOT NULL,
								    CONSTRAINT mib_tt UNIQUE NULLS NOT DISTINCT ("mib_id", "trap_type_id")
								);`,
	"public.device_indicator": `CREATE TABLE IF NOT EXISTS public.device_indicator (
								    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "description" TEXT,
								    "object_id" TEXT NOT NULL,
								    "contact" TEXT,
								    "name" TEXT,
								    "location" TEXT,
								    "services" SMALLINT,
								    CONSTRAINT device_indicator_tt UNIQUE NULLS NOT DISTINCT ("description", "object_id", "contact", "name", "location", "services")
								);`,
	"public.param_indicator": `CREATE TABLE IF NOT EXISTS public.param_indicator (
							       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							       "oid_id" UUID,
							       "dotter_notation" TEXT
							   );`,
	"public.mapping": `CREATE TABLE IF NOT EXISTS public.mapping (
					       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					       "indicator" BIGINT NOT NULL,
					       "param" BIGINT NOT NULL,
					       "frequency" SMALLINT NOT NULL,
					       "value" VARCHAR(255),
					       "coefficient" NUMERIC(38, 12),
					       "enum" JSONB,
					       "position" SMALLINT,
					       "from" BIGINT,
					       "position_type" SMALLINT
					   );`,
	"public.device_component": `CREATE TABLE IF NOT EXISTS public.device_component (
								    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								    "model" BIGINT NOT NULL,
								    "internal_order" INTEGER DEFAULT 1,
								    "parent" BIGINT
								);`,
	"public.device_component_mapping": `CREATE TABLE IF NOT EXISTS public.device_component_mapping (
										    "device_component_id" BIGINT NOT NULL,
										    "mapping_id" BIGINT NOT NULL,
										    PRIMARY KEY ("device_component_id", "mapping_id")
										);`,
	"public.configuration": `CREATE TABLE IF NOT EXISTS public.configuration (
							     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							     "indicator" BIGINT NOT NULL,
							     "device_component_id" BIGINT
							 );`,
	"public.default_configuration": `CREATE TABLE IF NOT EXISTS public.default_configuration (
									     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									     "indicator" BIGINT NOT NULL,
									     "device_component_id" BIGINT
									 );`,
	"public.threshold": `CREATE TABLE IF NOT EXISTS public.threshold (
						     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						     "name" VARCHAR(255) NOT NULL,
						     "description" TEXT,
						     "author" VARCHAR(255),
						     "created" TIMESTAMP,
						     "query" TEXT UNIQUE NOT NULL
						 );`,
	"public.device_snmp": `CREATE TABLE IF NOT EXISTS public.device_snmp (
						       "host" VARCHAR(30) NOT NULL,
						       "port" INTEGER NOT NULL,
						       "community" VARCHAR(255) NOT NULL,
						       "version" SMALLINT NOT NULL,
						       "login" VARCHAR(255),
						       "password" TEXT,
						       "authentication" SMALLINT NOT NULL,
						       "privacy" SMALLINT NOT NULL,
						       "id" UUID UNIQUE NOT NULL,
						       "config" BIGINT,
						       PRIMARY KEY ("host", "port")
						   );`,
	"public.result": `CREATE TABLE IF NOT EXISTS public.result (
					      "host" VARCHAR(30) NOT NULL,
					      "port" INTEGER NOT NULL,
					      "component" BIGINT NOT NULL,
					      "internal_order" INTEGER DEFAULT 1,
					      "param" BIGINT NOT NULL,
					      "value" TEXT,
					      PRIMARY KEY ("host", "port", "component", "internal_order", "param")
					  );`,
	"public.affected_threshold": `CREATE TABLE IF NOT EXISTS public.affected_threshold (
								      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
								      "host" VARCHAR(30) NOT NULL,
								      "port" INTEGER NOT NULL,
								      "threshold" BIGINT NOT NULL,
								      "enabled" BOOLEAN DEFAULT true
								  );`,
	"public.affected_param": `CREATE TABLE IF NOT EXISTS public.affected_param (
							      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							      "host" VARCHAR(30) NOT NULL,
							      "port" INTEGER NOT NULL,
							      "component" BIGINT NOT NULL,
							      "internal_order" INTEGER DEFAULT 1,
							      "param" BIGINT NOT NULL
							  );`,
	"public.config_in_process": `CREATE TABLE IF NOT EXISTS public.config_in_process (
								     "host" VARCHAR(255) NOT NULL,
								     "port" INTEGER NOT NULL,
								     "protocol" SMALLINT NOT NULL,
								     PRIMARY KEY ("host", "port", "protocol")
								 );`,
}

type rawQueryResult struct {
	tableName string
	data      any
}

type tablePrintResult struct {
	tableName string
	rowCount  int
}

func ExportDatabase(ctx context.Context) error {
	var wg sync.WaitGroup
	var ch chan rawQueryResult
	var item rawQueryResult
	var results []tablePrintResult
	var idx int
	ch = make(chan rawQueryResult, 71)
	wg.Add(71)
	go func() {
		var list []dao.PollingProtocolDao
		var errFetch error
		list, errFetch = dao.GetAllPollingProtocolDao()
		if errFetch != nil {
			logger.Error("Error fetching polling_protocol: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.polling_protocol", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AccessDao
		var errFetch error
		list, errFetch = dao.GetAllAccessDao()
		if errFetch != nil {
			logger.Error("Error fetching access: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.access", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.VersionSnmpDao
		var errFetch error
		list, errFetch = dao.GetAllVersionSnmpDao()
		if errFetch != nil {
			logger.Error("Error fetching version_snmp: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.version_snmp", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AuthProtocolSnmpDao
		var errFetch error
		list, errFetch = dao.GetAllAuthProtocolSnmpDao()
		if errFetch != nil {
			logger.Error("Error fetching auth_protocol_snmp: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.auth_protocol_snmp", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.PrivacyProtocolSnmpDao
		var errFetch error
		list, errFetch = dao.GetAllPrivacyProtocolSnmpDao()
		if errFetch != nil {
			logger.Error("Error fetching privacy_protocol_snmp: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.privacy_protocol_snmp", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.OidTypeDao
		var errFetch error
		list, errFetch = dao.GetAllOidTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching oid_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.oid_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.LogicOperatorDao
		var errFetch error
		list, errFetch = dao.GetAllLogicOperatorDao()
		if errFetch != nil {
			logger.Error("Error fetching logic_operator: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.logic_operator", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AlarmLevelDao
		var errFetch error
		list, errFetch = dao.GetAllAlarmLevelDao()
		if errFetch != nil {
			logger.Error("Error fetching alarm_level: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.alarm_level", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.VarTypeDao
		var errFetch error
		list, errFetch = dao.GetAllVarTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching var_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.var_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.PollingFrequencyDao
		var errFetch error
		list, errFetch = dao.GetAllPollingFrequencyDao()
		if errFetch != nil {
			logger.Error("Error fetching polling_frequency: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.polling_frequency", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.OidAccessDao
		var errFetch error
		list, errFetch = dao.GetAllOidAccessDao()
		if errFetch != nil {
			logger.Error("Error fetching oid_access: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.oid_access", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.OidStatusDao
		var errFetch error
		list, errFetch = dao.GetAllOidStatusDao()
		if errFetch != nil {
			logger.Error("Error fetching oid_status: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.oid_status", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.Asn1TypeDao
		var errFetch error
		list, errFetch = dao.GetAllAsn1TypeDao()
		if errFetch != nil {
			logger.Error("Error fetching asn1_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.asn1_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.VendorDao
		var errFetch error
		list, errFetch = dao.GetAllVendorDao()
		if errFetch != nil {
			logger.Error("Error fetching vendor: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.vendor", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ComponentDao
		var errFetch error
		list, errFetch = dao.GetAllComponentDao()
		if errFetch != nil {
			logger.Error("Error fetching component: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.component", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ParamDao
		var errFetch error
		list, errFetch = dao.GetAllParamDao()
		if errFetch != nil {
			logger.Error("Error fetching param: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.param", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ComponentParamDao
		var errFetch error
		list, errFetch = dao.GetAllComponentParamDao()
		if errFetch != nil {
			logger.Error("Error fetching component_param: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.component_param", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AgentCapabilitiesDao
		var errFetch error
		list, errFetch = dao.GetAllAgentCapabilitiesDao()
		if errFetch != nil {
			logger.Error("Error fetching agent_capabilities: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.agent_capabilities", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AgentCapabilitiesModuleDao
		var errFetch error
		list, errFetch = dao.GetAllAgentCapabilitiesModuleDao()
		if errFetch != nil {
			logger.Error("Error fetching agent_capabilities_module: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.agent_capabilities_module", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AgentCapabilitiesModuleNotificationDao
		var errFetch error
		list, errFetch = dao.GetAllAgentCapabilitiesModuleNotificationDao()
		if errFetch != nil {
			logger.Error("Error fetching agent_capabilities_module_notification: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.agent_capabilities_module_notification", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AgentCapabilitiesModuleObjectDao
		var errFetch error
		list, errFetch = dao.GetAllAgentCapabilitiesModuleObjectDao()
		if errFetch != nil {
			logger.Error("Error fetching agent_capabilities_module_object: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.agent_capabilities_module_object", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ChoiceDao
		var errFetch error
		list, errFetch = dao.GetAllChoiceDao()
		if errFetch != nil {
			logger.Error("Error fetching choice: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.choice", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ExplicitDao
		var errFetch error
		list, errFetch = dao.GetAllExplicitDao()
		if errFetch != nil {
			logger.Error("Error fetching explicit: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.explicit", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ImplicitDao
		var errFetch error
		list, errFetch = dao.GetAllImplicitDao()
		if errFetch != nil {
			logger.Error("Error fetching implicit: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.implicit", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ImportDao
		var errFetch error
		list, errFetch = dao.GetAllImportDao()
		if errFetch != nil {
			logger.Error("Error fetching import: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.import", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibDao
		var errFetch error
		list, errFetch = dao.GetAllMibDao()
		if errFetch != nil {
			logger.Error("Error fetching mib: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ModuleComplianceDao
		var errFetch error
		list, errFetch = dao.GetAllModuleComplianceDao()
		if errFetch != nil {
			logger.Error("Error fetching module_compliance: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.module_compliance", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ModuleComplianceModuleDao
		var errFetch error
		list, errFetch = dao.GetAllModuleComplianceModuleDao()
		if errFetch != nil {
			logger.Error("Error fetching module_compliance_module: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.module_compliance_module", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ModuleComplianceModuleGroupDao
		var errFetch error
		list, errFetch = dao.GetAllModuleComplianceModuleGroupDao()
		if errFetch != nil {
			logger.Error("Error fetching module_compliance_module_group: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.module_compliance_module_group", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ModuleComplianceModuleObjectDao
		var errFetch error
		list, errFetch = dao.GetAllModuleComplianceModuleObjectDao()
		if errFetch != nil {
			logger.Error("Error fetching module_compliance_module_object: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.module_compliance_module_object", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ModuleIdentityDao
		var errFetch error
		list, errFetch = dao.GetAllModuleIdentityDao()
		if errFetch != nil {
			logger.Error("Error fetching module_identity: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.module_identity", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.NotificationGroupDao
		var errFetch error
		list, errFetch = dao.GetAllNotificationGroupDao()
		if errFetch != nil {
			logger.Error("Error fetching notification_group: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.notification_group", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.NotificationTypeDao
		var errFetch error
		list, errFetch = dao.GetAllNotificationTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching notification_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.notification_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ObjectGroupDao
		var errFetch error
		list, errFetch = dao.GetAllObjectGroupDao()
		if errFetch != nil {
			logger.Error("Error fetching object_group: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.object_group", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ObjectIdentifierDao
		var errFetch error
		list, errFetch = dao.GetAllObjectIdentifierDao()
		if errFetch != nil {
			logger.Error("Error fetching object_identifier: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.object_identifier", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ObjectIdentityDao
		var errFetch error
		list, errFetch = dao.GetAllObjectIdentityDao()
		if errFetch != nil {
			logger.Error("Error fetching object_identity: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.object_identity", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ObjectTypeDao
		var errFetch error
		list, errFetch = dao.GetAllObjectTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching object_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.object_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.OidDao
		var errFetch error
		list, errFetch = dao.GetAllOidDao()
		if errFetch != nil {
			logger.Error("Error fetching oid: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.oid", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.RevisionDao
		var errFetch error
		list, errFetch = dao.GetAllRevisionDao()
		if errFetch != nil {
			logger.Error("Error fetching revision: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.revision", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.SequenceDao
		var errFetch error
		list, errFetch = dao.GetAllSequenceDao()
		if errFetch != nil {
			logger.Error("Error fetching sequence: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.sequence", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.TextualConventionDao
		var errFetch error
		list, errFetch = dao.GetAllTextualConventionDao()
		if errFetch != nil {
			logger.Error("Error fetching textual_convention: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.textual_convention", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.TrapTypeDao
		var errFetch error
		list, errFetch = dao.GetAllTrapTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching trap_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.trap_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToAgentCapabilitiesDao
		var errFetch error
		list, errFetch = dao.GetAllMibToAgentCapabilitiesDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_agent_capabilities: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_agent_capabilities", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToChoiceDao
		var errFetch error
		list, errFetch = dao.GetAllMibToChoiceDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_choice: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_choice", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToExplicitDao
		var errFetch error
		list, errFetch = dao.GetAllMibToExplicitDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_explicit: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_explicit", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToImplicitDao
		var errFetch error
		list, errFetch = dao.GetAllMibToImplicitDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_implicit: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_implicit", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToImportDao
		var errFetch error
		list, errFetch = dao.GetAllMibToImportDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_import: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_import", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToModuleComplianceDao
		var errFetch error
		list, errFetch = dao.GetAllMibToModuleComplianceDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_module_compliance: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_module_compliance", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToModuleIdentityDao
		var errFetch error
		list, errFetch = dao.GetAllMibToModuleIdentityDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_module_identity: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_module_identity", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToNotificationGroupDao
		var errFetch error
		list, errFetch = dao.GetAllMibToNotificationGroupDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_notification_group: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_notification_group", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToNotificationTypeDao
		var errFetch error
		list, errFetch = dao.GetAllMibToNotificationTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_notification_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_notification_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToObjectGroupDao
		var errFetch error
		list, errFetch = dao.GetAllMibToObjectGroupDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_object_group: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_object_group", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToObjectIdentifierDao
		var errFetch error
		list, errFetch = dao.GetAllMibToObjectIdentifierDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_object_identifier: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_object_identifier", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToObjectIdentityDao
		var errFetch error
		list, errFetch = dao.GetAllMibToObjectIdentityDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_object_identity: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_object_identity", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToObjectTypeDao
		var errFetch error
		list, errFetch = dao.GetAllMibToObjectTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_object_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_object_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToSequenceDao
		var errFetch error
		list, errFetch = dao.GetAllMibToSequenceDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_sequence: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_sequence", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToTextualConventionDao
		var errFetch error
		list, errFetch = dao.GetAllMibToTextualConventionDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_textual_convention: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_textual_convention", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MibToTrapTypeDao
		var errFetch error
		list, errFetch = dao.GetAllMibToTrapTypeDao()
		if errFetch != nil {
			logger.Error("Error fetching mib_to_trap_type: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mib_to_trap_type", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.DeviceIndicatorDao
		var errFetch error
		list, errFetch = dao.GetAllDeviceIndicatorDao()
		if errFetch != nil {
			logger.Error("Error fetching device_indicator: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.device_indicator", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ParamIndicatorDao
		var errFetch error
		list, errFetch = dao.GetAllParamIndicatorDao()
		if errFetch != nil {
			logger.Error("Error fetching param_indicator: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.param_indicator", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.MappingDao
		var errFetch error
		list, errFetch = dao.GetAllMappingDao()
		if errFetch != nil {
			logger.Error("Error fetching mapping: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.mapping", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.DeviceComponentDao
		var errFetch error
		list, errFetch = dao.GetAllDeviceComponentDao()
		if errFetch != nil {
			logger.Error("Error fetching device_component: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.device_component", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.DeviceComponentMappingDao
		var errFetch error
		list, errFetch = dao.GetAllDeviceComponentMappingDao()
		if errFetch != nil {
			logger.Error("Error fetching device_component_mapping: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.device_component_mapping", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ConfigurationDao
		var errFetch error
		list, errFetch = dao.GetAllConfigurationDao()
		if errFetch != nil {
			logger.Error("Error fetching configuration: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.configuration", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.DefaultConfigurationDao
		var errFetch error
		list, errFetch = dao.GetAllDefaultConfigurationDao()
		if errFetch != nil {
			logger.Error("Error fetching default_configuration: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.default_configuration", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ThresholdDao
		var errFetch error
		list, errFetch = dao.GetAllThresholdDao()
		if errFetch != nil {
			logger.Error("Error fetching threshold: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.threshold", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.DeviceSnmpDao
		var errFetch error
		list, errFetch = dao.GetAllDeviceSnmpDao()
		if errFetch != nil {
			logger.Error("Error fetching device_snmp: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.device_snmp", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ResultDao
		var errFetch error
		list, errFetch = dao.GetAllResultDao()
		if errFetch != nil {
			logger.Error("Error fetching result: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.result", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AffectedThresholdDao
		var errFetch error
		list, errFetch = dao.GetAllAffectedThresholdDao()
		if errFetch != nil {
			logger.Error("Error fetching affected_threshold: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.affected_threshold", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.AffectedParamDao
		var errFetch error
		list, errFetch = dao.GetAllAffectedParamDao()
		if errFetch != nil {
			logger.Error("Error fetching affected_param: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.affected_param", data: list}
		wg.Done()
	}()
	go func() {
		var list []dao.ConfigInProcessDao
		var errFetch error
		list, errFetch = dao.GetAllConfigInProcessDao()
		if errFetch != nil {
			logger.Error("Error fetching config_in_process: %v", errFetch)
		}
		ch <- rawQueryResult{tableName: "public.config_in_process", data: list}
		wg.Done()
	}()
	go func() {
		wg.Wait()
		close(ch)
	}()
	for item = range ch {
		var count int
		switch v := item.data.(type) {
		case []dao.PollingProtocolDao:
			count = len(v)
		case []dao.AccessDao:
			count = len(v)
		case []dao.VersionSnmpDao:
			count = len(v)
		case []dao.AuthProtocolSnmpDao:
			count = len(v)
		case []dao.PrivacyProtocolSnmpDao:
			count = len(v)
		case []dao.OidTypeDao:
			count = len(v)
		case []dao.LogicOperatorDao:
			count = len(v)
		case []dao.AlarmLevelDao:
			count = len(v)
		case []dao.VarTypeDao:
			count = len(v)
		case []dao.PollingFrequencyDao:
			count = len(v)
		case []dao.OidAccessDao:
			count = len(v)
		case []dao.OidStatusDao:
			count = len(v)
		case []dao.Asn1TypeDao:
			count = len(v)
		case []dao.VendorDao:
			count = len(v)
		case []dao.ComponentDao:
			count = len(v)
		case []dao.ParamDao:
			count = len(v)
		case []dao.ComponentParamDao:
			count = len(v)
		case []dao.AgentCapabilitiesDao:
			count = len(v)
		case []dao.AgentCapabilitiesModuleDao:
			count = len(v)
		case []dao.AgentCapabilitiesModuleNotificationDao:
			count = len(v)
		case []dao.AgentCapabilitiesModuleObjectDao:
			count = len(v)
		case []dao.ChoiceDao:
			count = len(v)
		case []dao.ExplicitDao:
			count = len(v)
		case []dao.ImplicitDao:
			count = len(v)
		case []dao.ImportDao:
			count = len(v)
		case []dao.MibDao:
			count = len(v)
		case []dao.ModuleComplianceDao:
			count = len(v)
		case []dao.ModuleComplianceModuleDao:
			count = len(v)
		case []dao.ModuleComplianceModuleGroupDao:
			count = len(v)
		case []dao.ModuleComplianceModuleObjectDao:
			count = len(v)
		case []dao.ModuleIdentityDao:
			count = len(v)
		case []dao.NotificationGroupDao:
			count = len(v)
		case []dao.NotificationTypeDao:
			count = len(v)
		case []dao.ObjectGroupDao:
			count = len(v)
		case []dao.ObjectIdentifierDao:
			count = len(v)
		case []dao.ObjectIdentityDao:
			count = len(v)
		case []dao.ObjectTypeDao:
			count = len(v)
		case []dao.OidDao:
			count = len(v)
		case []dao.RevisionDao:
			count = len(v)
		case []dao.SequenceDao:
			count = len(v)
		case []dao.TextualConventionDao:
			count = len(v)
		case []dao.TrapTypeDao:
			count = len(v)
		case []dao.MibToAgentCapabilitiesDao:
			count = len(v)
		case []dao.MibToChoiceDao:
			count = len(v)
		case []dao.MibToExplicitDao:
			count = len(v)
		case []dao.MibToImplicitDao:
			count = len(v)
		case []dao.MibToImportDao:
			count = len(v)
		case []dao.MibToModuleComplianceDao:
			count = len(v)
		case []dao.MibToModuleIdentityDao:
			count = len(v)
		case []dao.MibToNotificationGroupDao:
			count = len(v)
		case []dao.MibToNotificationTypeDao:
			count = len(v)
		case []dao.MibToObjectGroupDao:
			count = len(v)
		case []dao.MibToObjectIdentifierDao:
			count = len(v)
		case []dao.MibToObjectIdentityDao:
			count = len(v)
		case []dao.MibToObjectTypeDao:
			count = len(v)
		case []dao.MibToSequenceDao:
			count = len(v)
		case []dao.MibToTextualConventionDao:
			count = len(v)
		case []dao.MibToTrapTypeDao:
			count = len(v)
		case []dao.DeviceIndicatorDao:
			count = len(v)
		case []dao.ParamIndicatorDao:
			count = len(v)
		case []dao.MappingDao:
			count = len(v)
		case []dao.DeviceComponentDao:
			count = len(v)
		case []dao.DeviceComponentMappingDao:
			count = len(v)
		case []dao.ConfigurationDao:
			count = len(v)
		case []dao.DefaultConfigurationDao:
			count = len(v)
		case []dao.ThresholdDao:
			count = len(v)
		case []dao.DeviceSnmpDao:
			count = len(v)
		case []dao.ResultDao:
			count = len(v)
		case []dao.AffectedThresholdDao:
			count = len(v)
		case []dao.AffectedParamDao:
			count = len(v)
		case []dao.ConfigInProcessDao:
			count = len(v)
		default:
			count = 0
		}
		results = append(results, tablePrintResult{tableName: item.tableName, rowCount: count})
	}
	sort.Slice(results, func(i int, j int) bool {
		var isGreater bool
		isGreater = results[i].tableName > results[j].tableName
		return !isGreater
	})
	idx = len(results)
	for idx > 0 {
		var outputItem tablePrintResult
		idx--
		outputItem = results[len(results)-1-idx]
		fmt.Printf("%-50s | Rows: %d\n", outputItem.tableName, outputItem.rowCount)
	}
	return nil
}
