package service

import (
	"configurator/internal/dao"
	"configurator/internal/logger"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

var tableSchemas = map[string]string{
	"public.polling_protocol": `CREATE TABLE IF NOT EXISTS public.polling_protocol
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10)
);`,
	"public.access": `CREATE TABLE IF NOT EXISTS public.access
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(5)
);`,
	"public.version_snmp": `CREATE TABLE IF NOT EXISTS public.version_snmp
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(3)
);`,
	"public.auth_protocol_snmp": `CREATE TABLE IF NOT EXISTS public.auth_protocol_snmp
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10)
);`,
	"public.privacy_protocol_snmp": `CREATE TABLE IF NOT EXISTS public.privacy_protocol_snmp
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10)
);`,
	"public.oid_type": `CREATE TABLE IF NOT EXISTS public.oid_type
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(17)
);`,
	"public.logic_operator": `CREATE TABLE IF NOT EXISTS public.logic_operator
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(12) NOT NULL,
    "type" VARCHAR(15) NOT NULL,
    "precedence" SMALLINT NOT NULL,
    "arity" SMALLINT NOT NULL
);`,
	"public.alarm_level": `CREATE TABLE IF NOT EXISTS public.alarm_level
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(12)
);`,
	"public.var_type": `CREATE TABLE IF NOT EXISTS public.var_type
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(17)
);`,
	"public.polling_frequency": `CREATE TABLE IF NOT EXISTS public.polling_frequency
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(6)
);`,
	"public.oid_access": `CREATE TABLE IF NOT EXISTS public.oid_access
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(21) NOT NULL
);`,
	"public.oid_status": `CREATE TABLE IF NOT EXISTS public.oid_status
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(10) NOT NULL
);`,
	"public.asn1_type": `CREATE TABLE IF NOT EXISTS public.asn1_type
(
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(18) NOT NULL
);`,
	"public.vendor": `CREATE TABLE IF NOT EXISTS public.vendor
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "number" INTEGER NOT NULL,
    "contact" TEXT,
    "email" TEXT,
    "directory" VARCHAR(255)
);`,
	"public.component": `CREATE TABLE IF NOT EXISTS public.component
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR NOT NULL,
    "name_en" VARCHAR NOT NULL,
    "name_ru" VARCHAR NOT NULL,
    "plural_name_en" VARCHAR NOT NULL,
    "plural_name_ru" VARCHAR NOT NULL,
    "base_component" BIGINT,
    "description_en" TEXT,
    "description_ru" TEXT,
    "access" SMALLINT NOT NULL
);`,
	"public.param": `CREATE TABLE IF NOT EXISTS public.param
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR NOT NULL,
    "name_en" VARCHAR NOT NULL,
    "name_ru" VARCHAR NOT NULL,
    "type" SMALLINT NOT NULL,
    "value" TEXT,
    "description_en" TEXT,
    "description_ru" TEXT,
    "units_en" TEXT,
    "units_ru" TEXT,
    "access" SMALLINT NOT NULL,
    "saved" BOOLEAN NOT NULL,
    "visible" BOOLEAN NOT NULL
);`,
	"public.component_param": `CREATE TABLE IF NOT EXISTS public.component_param
(
    "component_id" BIGINT NOT NULL,
    "param_id" BIGINT NOT NULL,
    PRIMARY KEY ("component_id", "param_id")
);`,
	"public.agent_capabilities": `CREATE TABLE IF NOT EXISTS public.agent_capabilities
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "product_release" TEXT,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);`,
	"public.agent_capabilities_module": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supports" VARCHAR(255),
    "includes" VARCHAR(255)[]
);`,
	"public.agent_capabilities_module_notification": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_notification
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "variation" VARCHAR(255),
    "access" SMALLINT,
    "description" TEXT
);`,
	"public.agent_capabilities_module_object": `CREATE TABLE IF NOT EXISTS public.agent_capabilities_module_object
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "variation" VARCHAR(255),
    "syntax" VARCHAR(255),
    "write_syntax" VARCHAR(255),
    "access" SMALLINT,
    "creation_requires" VARCHAR(255)[],
    "defval" VARCHAR(255),
    "description" TEXT
);`,
	"public.choice": `CREATE TABLE IF NOT EXISTS public.choice
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "choices" JSONB NOT NULL
);`,
	"public.explicit": `CREATE TABLE IF NOT EXISTS public.explicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "value" TEXT NOT NULL
);`,
	"public.implicit": `CREATE TABLE IF NOT EXISTS public.implicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "application" SMALLINT NOT NULL,
    "value" VARCHAR(255) NOT NULL
);`,
	"public.import": `CREATE TABLE IF NOT EXISTS public.import
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "param" VARCHAR(255) NOT NULL,
    "from" VARCHAR(255) NOT NULL
);`,
	"public.mib": `CREATE TABLE IF NOT EXISTS public.mib
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "path" TEXT NOT NULL,
    "name" VARCHAR(50),
    "vendor" BIGINT
);`,
	"public.module_compliance": `CREATE TABLE IF NOT EXISTS public.module_compliance
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);`,
	"public.module_compliance_module": `CREATE TABLE IF NOT EXISTS public.module_compliance_module
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "mandatory_groups" VARCHAR(255)[]
);`,
	"public.module_compliance_module_group": `CREATE TABLE IF NOT EXISTS public.module_compliance_module_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT
);`,
	"public.module_compliance_module_object": `CREATE TABLE IF NOT EXISTS public.module_compliance_module_object
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "syntax" VARCHAR(255),
    "write_syntax" VARCHAR(255),
    "access" SMALLINT,
    "description" TEXT
);`,
	"public.module_identity": `CREATE TABLE IF NOT EXISTS public.module_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "last_updated" TIMESTAMP,
    "organization" VARCHAR(255),
    "contact_info" TEXT,
    "description"  TEXT
);`,
	"public.notification_group": `CREATE TABLE IF NOT EXISTS public.notification_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "notifications" VARCHAR(255)[],
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);`,
	"public.notification_type": `CREATE TABLE IF NOT EXISTS public.notification_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "objects" VARCHAR(255)[],
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);`,
	"public.object_group": `CREATE TABLE IF NOT EXISTS public.object_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "objects" VARCHAR[],
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);`,
	"public.object_identifier": `CREATE TABLE IF NOT EXISTS public.object_identifier
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "num_oid" VARCHAR[],
    "str_oid" VARCHAR[],
    "parent" VARCHAR(255),
    "type" SMALLINT NOT NULL
);`,
	"public.object_identity": `CREATE TABLE IF NOT EXISTS public.object_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT
);`,
	"public.object_type": `CREATE TABLE IF NOT EXISTS public.object_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "syntax" TEXT,
    "units" VARCHAR(255),
    "access" SMALLINT,
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT,
    "index" VARCHAR(255)[],
    "augments" VARCHAR(255)[],
    "default_value" VARCHAR(255)
);`,
	"public.oid": `CREATE TABLE IF NOT EXISTS public.oid
(
    "id" UUID PRIMARY KEY,
    "mib" BIGINT,
    "type" SMALLINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "number" INTEGER,
    "dotter_notation" TEXT NOT NULL,
    "object_descriptor" TEXT NOT NULL,
    "syntax" TEXT,
    "enum" JSONB,
    "status" SMALLINT,
    "access" SMALLINT,
    "units" VARCHAR(255),
    "description" TEXT,
    "category" VARCHAR(255)
);`,
	"public.revision": `CREATE TABLE IF NOT EXISTS public.revision
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "revision" TIMESTAMP,
    "description" TEXT
);`,
	"public.sequence": `CREATE TABLE IF NOT EXISTS public.sequence
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "pairs" JSONB NOT NULL
);`,
	"public.textual_convention": `CREATE TABLE IF NOT EXISTS public.textual_convention
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "display_hint" VARCHAR(255),
    "status" SMALLINT,
    "description" TEXT,
    "reference" TEXT,
    "syntax" TEXT
);`,
	"public.trap_type": `CREATE TABLE IF NOT EXISTS public.trap_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "variables" VARCHAR(255)[],
    "description" TEXT,
    "reference" TEXT
);`,
	"public.mib_to_agent_capabilities": `CREATE TABLE IF NOT EXISTS public.mib_to_agent_capabilities
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "agent_capabilities_id" BIGINT NOT NULL,
    "agent_capabilities_module_id" BIGINT,
    "agent_capabilities_module_notification_id" BIGINT,
    "agent_capabilities_module_object_id" BIGINT
);`,
	"public.mib_to_choice": `CREATE TABLE IF NOT EXISTS public.mib_to_choice
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "choice_id" BIGINT NOT NULL
);`,
	"public.mib_to_explicit": `CREATE TABLE IF NOT EXISTS public.mib_to_explicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "explicit_id" BIGINT NOT NULL
);`,
	"public.mib_to_implicit": `CREATE TABLE IF NOT EXISTS public.mib_to_implicit
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "implicit_id" BIGINT NOT NULL
);`,
	"public.mib_to_import": `CREATE TABLE IF NOT EXISTS public.mib_to_import
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "import_id" BIGINT NOT NULL
);`,
	"public.mib_to_module_compliance": `CREATE TABLE IF NOT EXISTS public.mib_to_module_compliance
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "module_compliance_id" BIGINT NOT NULL,
    "module_compliance_module_id" BIGINT,
    "module_compliance_module_group_id" BIGINT,
    "module_compliance_module_object_id" BIGINT
);`,
	"public.mib_to_module_identity": `CREATE TABLE IF NOT EXISTS public.mib_to_module_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "module_identity_id" BIGINT NOT NULL,
    "revision_id" BIGINT
);`,
	"public.mib_to_notification_group": `CREATE TABLE IF NOT EXISTS public.mib_to_notification_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "notification_group_id" BIGINT NOT NULL
);`,
	"public.mib_to_notification_type": `CREATE TABLE IF NOT EXISTS public.mib_to_notification_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "notification_type_id" BIGINT NOT NULL
);`,
	"public.mib_to_object_group": `CREATE TABLE IF NOT EXISTS public.mib_to_object_group
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_group_id" BIGINT NOT NULL
);`,
	"public.mib_to_object_identifier": `CREATE TABLE IF NOT EXISTS public.mib_to_object_identifier
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_identifier_id" BIGINT NOT NULL
);`,
	"public.mib_to_object_identity": `CREATE TABLE IF NOT EXISTS public.mib_to_object_identity
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_identity_id" BIGINT NOT NULL
);`,
	"public.mib_to_object_type": `CREATE TABLE IF NOT EXISTS public.mib_to_object_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "object_type_id" BIGINT NOT NULL
);`,
	"public.mib_to_sequence": `CREATE TABLE IF NOT EXISTS public.mib_to_sequence
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "sequence_id" BIGINT NOT NULL
);`,
	"public.mib_to_textual_convention": `CREATE TABLE IF NOT EXISTS public.mib_to_textual_convention
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "textual_convention_id" BIGINT NOT NULL
);`,
	"public.mib_to_trap_type": `CREATE TABLE IF NOT EXISTS public.mib_to_trap_type
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mib_id" BIGINT NOT NULL,
    "trap_type_id" BIGINT NOT NULL
);`,
	"public.device_indicator": `CREATE TABLE IF NOT EXISTS public.device_indicator
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "description" TEXT,
    "object_id" TEXT NOT NULL,
    "contact" TEXT,
    "name" TEXT,
    "location" TEXT,
    "services" SMALLINT
);`,
	"public.param_indicator": `CREATE TABLE IF NOT EXISTS public.param_indicator
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "oid_id" UUID,
    "dotter_notation" TEXT
);`,
	"public.mapping": `CREATE TABLE IF NOT EXISTS public.mapping
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indicator" BIGINT NOT NULL,
    "param" BIGINT NOT NULL,
    "frequency" SMALLINT NOT NULL,
    "value" VARCHAR(255),
    "coefficient" NUMERIC(38, 12),
    "enum" JSONB,
    "position" SMALLINT,
    "from" BIGINT,
    "position_type" SMALLINT
);`,
	"public.device_component": `CREATE TABLE IF NOT EXISTS public.device_component
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "model" BIGINT NOT NULL,
    "internal_order" INTEGER DEFAULT 1,
    "parent" BIGINT
);`,
	"public.device_component_mapping": `CREATE TABLE IF NOT EXISTS public.device_component_mapping
(
    "device_component_id" BIGINT NOT NULL,
    "mapping_id" BIGINT NOT NULL,
    PRIMARY KEY ("device_component_id", "mapping_id")
);`,
	"public.configuration": `CREATE TABLE IF NOT EXISTS public.configuration
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indicator" BIGINT NOT NULL,
    "device_component_id" BIGINT
);`,
	"public.default_configuration": `CREATE TABLE IF NOT EXISTS public.default_configuration
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indicator" BIGINT NOT NULL,
    "device_component_id" BIGINT
);`,
	"public.threshold": `CREATE TABLE IF NOT EXISTS public.threshold
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "author" VARCHAR(255),
    "created" TIMESTAMP,
    "query" TEXT NOT NULL
);`,
	"public.device_snmp": `CREATE TABLE IF NOT EXISTS public.device_snmp
(
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "community" VARCHAR(255) NOT NULL,
    "version" SMALLINT NOT NULL,
    "login" VARCHAR(255),
    "password" TEXT,
    "authentication" SMALLINT NOT NULL,
    "privacy" SMALLINT NOT NULL,
    "id" UUID UNIQUE NOT NULL,
    "config" BIGINT,
    PRIMARY KEY ("host", "port")
);`,
	"public.result": `CREATE TABLE IF NOT EXISTS public.result
(
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "component" BIGINT NOT NULL,
    "internal_order" INTEGER DEFAULT 1,
    "param" BIGINT NOT NULL,
    "value" TEXT,
    PRIMARY KEY ("host", "port", "component", "internal_order", "param")
);`,
	"public.affected_threshold": `CREATE TABLE IF NOT EXISTS public.affected_threshold
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "threshold" BIGINT NOT NULL,
    "enabled" BOOLEAN DEFAULT true
);`,
	"public.affected_param": `CREATE TABLE IF NOT EXISTS public.affected_param
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "host" VARCHAR(30) NOT NULL,
    "port" INTEGER NOT NULL,
    "component" BIGINT NOT NULL,
    "internal_order" INTEGER DEFAULT 1,
    "param" BIGINT NOT NULL
);`,
	"public.config_in_process": `CREATE TABLE IF NOT EXISTS public.config_in_process
(
    "host" VARCHAR(255) NOT NULL,
    "port" INTEGER NOT NULL,
    "protocol" SMALLINT NOT NULL,
    PRIMARY KEY ("host", "port", "protocol")
);`,
}

var constraintsSQL = `ALTER TABLE public.logic_operator 
  ADD CONSTRAINT "logic_operator_value_key" UNIQUE ("value"),
  ADD CONSTRAINT "logic_operator_type_check" CHECK ("type" IN ('LOGICAL', 'COMPARISON', 'BRACKET')),
  ADD CONSTRAINT "logic_operator_arity_check" CHECK ("arity" IN (1, 2));

ALTER TABLE public.oid_access 
  ADD CONSTRAINT "oid_access_value_key" UNIQUE ("value");

ALTER TABLE public.oid_status 
  ADD CONSTRAINT "oid_status_value_key" UNIQUE ("value");

ALTER TABLE public.asn1_type 
  ADD CONSTRAINT "asn1_type_value_key" UNIQUE ("value");

ALTER TABLE public.vendor 
  ADD CONSTRAINT "vendor_number_key" UNIQUE ("number");

ALTER TABLE public.agent_capabilities 
  ADD CONSTRAINT "agent_capabilities_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.agent_capabilities_module_notification 
  ADD CONSTRAINT "agent_capabilities_module_notification_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.agent_capabilities_module_object 
  ADD CONSTRAINT "agent_capabilities_module_object_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.mib 
  ADD CONSTRAINT "mib_path_key" UNIQUE ("path"),
  ADD CONSTRAINT "mib_vendor_fkey" FOREIGN KEY ("vendor") REFERENCES public.vendor ("id") ON DELETE CASCADE;

ALTER TABLE public.module_compliance 
  ADD CONSTRAINT "module_compliance_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.module_compliance_module_object 
  ADD CONSTRAINT "module_compliance_module_object_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.notification_group 
  ADD CONSTRAINT "notification_group_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.notification_type 
  ADD CONSTRAINT "notification_type_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.object_group 
  ADD CONSTRAINT "object_group_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.object_identifier 
  ADD CONSTRAINT "object_identifier_type_fkey" FOREIGN KEY ("type") REFERENCES public.asn1_type ("id") ON DELETE CASCADE;

ALTER TABLE public.object_identity 
  ADD CONSTRAINT "object_identity_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.object_type 
  ADD CONSTRAINT "object_type_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "object_type_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.textual_convention 
  ADD CONSTRAINT "textual_convention_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE;

ALTER TABLE public.mib_to_agent_capabilities 
  ADD CONSTRAINT "mib_to_agent_capabilities_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_id_fkey" FOREIGN KEY ("agent_capabilities_id") REFERENCES public.agent_capabilities ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_module_id_fkey" FOREIGN KEY ("agent_capabilities_module_id") REFERENCES public.agent_capabilities_module ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_module_notification_id_fkey" FOREIGN KEY ("agent_capabilities_module_notification_id") REFERENCES public.agent_capabilities_module_notification ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_agent_capabilities_agent_capabilities_module_object_id_fkey" FOREIGN KEY ("agent_capabilities_module_object_id") REFERENCES public.agent_capabilities_module_object ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_ac" UNIQUE NULLS NOT DISTINCT ("mib_id", "agent_capabilities_id", "agent_capabilities_module_id", "agent_capabilities_module_notification_id", "agent_capabilities_module_object_id");

ALTER TABLE public.mib_to_choice 
  ADD CONSTRAINT "mib_to_choice_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_choice_choice_id_fkey" FOREIGN KEY ("choice_id") REFERENCES public.choice ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_c" UNIQUE NULLS NOT DISTINCT ("mib_id", "choice_id");

ALTER TABLE public.mib_to_explicit 
  ADD CONSTRAINT "mib_to_explicit_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_explicit_explicit_id_fkey" FOREIGN KEY ("explicit_id") REFERENCES public.explicit ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_et" UNIQUE NULLS NOT DISTINCT ("mib_id", "explicit_id");

ALTER TABLE public.mib_to_implicit 
  ADD CONSTRAINT "mib_to_implicit_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_implicit_implicit_id_fkey" FOREIGN KEY ("implicit_id") REFERENCES public.implicit ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_it" UNIQUE NULLS NOT DISTINCT ("mib_id", "implicit_id");

ALTER TABLE public.mib_to_import 
  ADD CONSTRAINT "mib_to_import_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_import_import_id_fkey" FOREIGN KEY ("import_id") REFERENCES public.import ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_imp" UNIQUE NULLS NOT DISTINCT ("mib_id", "import_id");

ALTER TABLE public.mib_to_module_compliance 
  ADD CONSTRAINT "mib_to_module_compliance_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_id_fkey" FOREIGN KEY ("module_compliance_id") REFERENCES public.module_compliance ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_module_id_fkey" FOREIGN KEY ("module_compliance_module_id") REFERENCES public.module_compliance_module ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_module_group_id_fkey" FOREIGN KEY ("module_compliance_module_group_id") REFERENCES public.module_compliance_module_group ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_compliance_module_compliance_module_object_id_fkey" FOREIGN KEY ("module_compliance_module_object_id") REFERENCES public.module_compliance_module_object ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_mc" UNIQUE NULLS NOT DISTINCT ("mib_id", "module_compliance_id", "module_compliance_module_id", "module_compliance_module_group_id", "module_compliance_module_object_id");

ALTER TABLE public.mib_to_module_identity 
  ADD CONSTRAINT "mib_to_module_identity_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_identity_module_identity_id_fkey" FOREIGN KEY ("module_identity_id") REFERENCES public.module_identity ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_module_identity_revision_id_fkey" FOREIGN KEY ("revision_id") REFERENCES public.revision ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_mi_rev" UNIQUE NULLS NOT DISTINCT ("mib_id", "module_identity_id", "revision_id");

ALTER TABLE public.mib_to_notification_group 
  ADD CONSTRAINT "mib_to_notification_group_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_notification_group_notification_group_id_fkey" FOREIGN KEY ("notification_group_id") REFERENCES public.notification_group ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_ng" UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_group_id");

ALTER TABLE public.mib_to_notification_type 
  ADD CONSTRAINT "mib_to_notification_type_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_notification_type_notification_type_id_fkey" FOREIGN KEY ("notification_type_id") REFERENCES public.notification_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_nt" UNIQUE NULLS NOT DISTINCT ("mib_id", "notification_type_id");

ALTER TABLE public.mib_to_object_group 
  ADD CONSTRAINT "mib_to_object_group_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_group_object_group_id_fkey" FOREIGN KEY ("object_group_id") REFERENCES public.object_group ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_og" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_group_id");

ALTER TABLE public.mib_to_object_identifier 
  ADD CONSTRAINT "mib_to_object_identifier_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_identifier_object_identifier_id_fkey" FOREIGN KEY ("object_identifier_id") REFERENCES public.object_identifier ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_oif" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identifier_id");

ALTER TABLE public.mib_to_object_identity 
  ADD CONSTRAINT "mib_to_object_identity_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_identity_object_identity_id_fkey" FOREIGN KEY ("object_identity_id") REFERENCES public.object_identity ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_oit" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_identity_id");

ALTER TABLE public.mib_to_object_type 
  ADD CONSTRAINT "mib_to_object_type_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_object_type_object_type_id_fkey" FOREIGN KEY ("object_type_id") REFERENCES public.object_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_ot" UNIQUE NULLS NOT DISTINCT ("mib_id", "object_type_id");

ALTER TABLE public.mib_to_sequence 
  ADD CONSTRAINT "mib_to_sequence_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_sequence_sequence_id_fkey" FOREIGN KEY ("sequence_id") REFERENCES public.sequence ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_sec" UNIQUE NULLS NOT DISTINCT ("mib_id", "sequence_id");

ALTER TABLE public.mib_to_textual_convention 
  ADD CONSTRAINT "mib_to_textual_convention_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_textual_convention_textual_convention_id_fkey" FOREIGN KEY ("textual_convention_id") REFERENCES public.textual_convention ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_tc" UNIQUE NULLS NOT DISTINCT ("mib_id", "textual_convention_id");

ALTER TABLE public.mib_to_trap_type 
  ADD CONSTRAINT "mib_to_trap_type_mib_id_fkey" FOREIGN KEY ("mib_id") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_to_trap_type_trap_type_id_fkey" FOREIGN KEY ("trap_type_id") REFERENCES public.trap_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mib_tt" UNIQUE NULLS NOT DISTINCT ("mib_id", "trap_type_id");

ALTER TABLE public.oid 
  ADD CONSTRAINT "oid_mib_fkey" FOREIGN KEY ("mib") REFERENCES public.mib ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "oid_type_fkey" FOREIGN KEY ("type") REFERENCES public.asn1_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "oid_status_fkey" FOREIGN KEY ("status") REFERENCES public.oid_status ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "oid_access_fkey" FOREIGN KEY ("access") REFERENCES public.oid_access ("id") ON DELETE CASCADE;

ALTER TABLE public.component 
  ADD CONSTRAINT "component_base_component_fkey" FOREIGN KEY ("base_component") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "component_access_fkey" FOREIGN KEY ("access") REFERENCES public.access ("id") ON DELETE CASCADE;

ALTER TABLE public.param 
  ADD CONSTRAINT "param_type_fkey" FOREIGN KEY ("type") REFERENCES public.var_type ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "param_access_fkey" FOREIGN KEY ("access") REFERENCES public.access ("id") ON DELETE CASCADE;

ALTER TABLE public.component_param 
  ADD CONSTRAINT "component_param_component_id_fkey" FOREIGN KEY ("component_id") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "component_param_param_id_fkey" FOREIGN KEY ("param_id") REFERENCES public.param ("id") ON DELETE CASCADE;

ALTER TABLE public.device_indicator 
  ADD CONSTRAINT "device_indicator_tt" UNIQUE NULLS NOT DISTINCT ("description", "object_id", "contact", "name", "location", "services");

ALTER TABLE public.param_indicator 
  ADD CONSTRAINT "param_indicator_oid_id_fkey" FOREIGN KEY ("oid_id") REFERENCES public.oid ("id") ON DELETE CASCADE;

ALTER TABLE public.mapping 
  ADD CONSTRAINT "mapping_indicator_fkey" FOREIGN KEY ("indicator") REFERENCES public.param_indicator ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_param_fkey" FOREIGN KEY ("param") REFERENCES public.param ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_frequency_fkey" FOREIGN KEY ("frequency") REFERENCES public.polling_frequency ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_from_fkey" FOREIGN KEY ("from") REFERENCES public.mapping ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "mapping_position_type_fkey" FOREIGN KEY ("position_type") REFERENCES public.oid_type ("id") ON DELETE CASCADE;

ALTER TABLE public.device_component 
  ADD CONSTRAINT "device_component_model_fkey" FOREIGN KEY ("model") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_component_parent_fkey" FOREIGN KEY ("parent") REFERENCES public.device_component ("id") ON DELETE CASCADE;

ALTER TABLE public.device_component_mapping 
  ADD CONSTRAINT "device_component_mapping_device_component_id_fkey" FOREIGN KEY ("device_component_id") REFERENCES public.device_component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_component_mapping_mapping_id_fkey" FOREIGN KEY ("mapping_id") REFERENCES public.mapping ("id") ON DELETE CASCADE;

ALTER TABLE public.configuration 
  ADD CONSTRAINT "configuration_indicator_fkey" FOREIGN KEY ("indicator") REFERENCES public.device_indicator ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "configuration_device_component_id_fkey" FOREIGN KEY ("device_component_id") REFERENCES public.device_component ("id") ON DELETE CASCADE;

ALTER TABLE public.default_configuration 
  ADD CONSTRAINT "default_configuration_indicator_fkey" FOREIGN KEY ("indicator") REFERENCES public.device_indicator ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "default_configuration_device_component_id_fkey" FOREIGN KEY ("device_component_id") REFERENCES public.device_component ("id") ON DELETE CASCADE;

ALTER TABLE public.threshold 
  ADD CONSTRAINT "threshold_query_key" UNIQUE ("query");

ALTER TABLE public.device_snmp 
  ADD CONSTRAINT "device_snmp_version_fkey" FOREIGN KEY ("version") REFERENCES public.version_snmp ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_snmp_authentication_fkey" FOREIGN KEY ("authentication") REFERENCES public.auth_protocol_snmp ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_snmp_privacy_fkey" FOREIGN KEY ("privacy") REFERENCES public.privacy_protocol_snmp ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "device_snmp_config_fkey" FOREIGN KEY ("config") REFERENCES public.configuration ("id") ON DELETE CASCADE;

ALTER TABLE public.result 
  ADD CONSTRAINT "result_component_fkey" FOREIGN KEY ("component") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "result_param_fkey" FOREIGN KEY ("param") REFERENCES public.param ("id") ON DELETE CASCADE;

ALTER TABLE public.affected_threshold 
  ADD CONSTRAINT "affected_threshold_threshold_fkey" FOREIGN KEY ("threshold") REFERENCES public.threshold ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "affected_threshold_host_port_fkey" FOREIGN KEY ("host", "port") REFERENCES public.device_snmp ("host", "port") ON DELETE CASCADE;

ALTER TABLE public.affected_param 
  ADD CONSTRAINT "affected_param_component_fkey" FOREIGN KEY ("component") REFERENCES public.component ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "affected_param_param_fkey" FOREIGN KEY ("param") REFERENCES public.param ("id") ON DELETE CASCADE,
  ADD CONSTRAINT "affected_param_host_port_fkey" FOREIGN KEY ("host", "port") REFERENCES public.device_snmp ("host", "port") ON DELETE CASCADE;

ALTER TABLE public.config_in_process 
  ADD CONSTRAINT "config_in_process_protocol_fkey" FOREIGN KEY ("protocol") REFERENCES public.polling_protocol ("id") ON DELETE CASCADE;`

type rawQueryResult struct {
	tableName string
	data      any
}

type tablePrintResult struct {
	tableName string
	rowCount  int
}

func ExportDatabase(ctx context.Context) error {
	var wg sync.WaitGroup
	var ch chan rawQueryResult
	var results []tablePrintResult
	var item rawQueryResult
	var outputItem tablePrintResult
	var outputDir string
	var idx int
	var err error
	var callers map[string]any
	var tName string
	var fn any
	var inArgs []reflect.Value
	outputDir = "sql"
	err = os.MkdirAll(outputDir, 0755)
	if err != nil {
		logger.Error("Failed to create output directory: %v", err)
		return err
	}
	ch = make(chan rawQueryResult, 72)
	results = make([]tablePrintResult, 0, 72)
	inArgs = []reflect.Value{reflect.ValueOf(ctx)}
	callers = map[string]any{
		"public.polling_protocol":                       dao.GetAllPollingProtocolDao,
		"public.access":                                 dao.GetAllAccessDao,
		"public.version_snmp":                           dao.GetAllVersionSnmpDao,
		"public.auth_protocol_snmp":                     dao.GetAllAuthProtocolSnmpDao,
		"public.privacy_protocol_snmp":                  dao.GetAllPrivacyProtocolSnmpDao,
		"public.oid_type":                               dao.GetAllOidTypeDao,
		"public.logic_operator":                         dao.GetAllLogicOperatorDao,
		"public.alarm_level":                            dao.GetAllAlarmLevelDao,
		"public.var_type":                               dao.GetAllVarTypeDao,
		"public.polling_frequency":                      dao.GetAllPollingFrequencyDao,
		"public.oid_access":                             dao.GetAllOidAccessDao,
		"public.oid_status":                             dao.GetAllOidStatusDao,
		"public.asn1_type":                              dao.GetAllAsn1TypeDao,
		"public.vendor":                                 dao.GetAllVendorDao,
		"public.component":                              dao.GetAllComponentDao,
		"public.param":                                  dao.GetAllParamDao,
		"public.component_param":                        dao.GetAllComponentParamDao,
		"public.agent_capabilities":                     dao.GetAllAgentCapabilitiesDao,
		"public.agent_capabilities_module":              dao.GetAllAgentCapabilitiesModuleDao,
		"public.agent_capabilities_module_notification": dao.GetAllAgentCapabilitiesModuleNotificationDao,
		"public.agent_capabilities_module_object":       dao.GetAllAgentCapabilitiesModuleObjectDao,
		"public.choice":                                 dao.GetAllChoiceDao,
		"public.explicit":                               dao.GetAllExplicitDao,
		"public.implicit":                               dao.GetAllImplicitDao,
		"public.import":                                 dao.GetAllImportDao,
		"public.mib":                                    dao.GetAllMibDao,
		"public.module_compliance":                      dao.GetAllModuleComplianceDao,
		"public.module_compliance_module":               dao.GetAllModuleComplianceModuleDao,
		"public.module_compliance_module_group":         dao.GetAllModuleComplianceModuleGroupDao,
		"public.module_compliance_module_object":        dao.GetAllModuleComplianceModuleObjectDao,
		"public.module_identity":                        dao.GetAllModuleIdentityDao,
		"public.notification_group":                     dao.GetAllNotificationGroupDao,
		"public.notification_type":                      dao.GetAllNotificationTypeDao,
		"public.object_group":                           dao.GetAllObjectGroupDao,
		"public.object_identifier":                      dao.GetAllObjectIdentifierDao,
		"public.object_identity":                        dao.GetAllObjectIdentityDao,
		"public.object_type":                            dao.GetAllObjectTypeDao,
		"public.oid":                                    dao.GetAllOidDao,
		"public.revision":                               dao.GetAllRevisionDao,
		"public.sequence":                               dao.GetAllSequenceDao,
		"public.textual_convention":                     dao.GetAllTextualConventionDao,
		"public.trap_type":                              dao.GetAllTrapTypeDao,
		"public.mib_to_agent_capabilities":              dao.GetAllMibToAgentCapabilitiesDao,
		"public.mib_to_choice":                          dao.GetAllMibToChoiceDao,
		"public.mib_to_explicit":                        dao.GetAllMibToExplicitDao,
		"public.mib_to_implicit":                        dao.GetAllMibToImplicitDao,
		"public.mib_to_import":                          dao.GetAllMibToImportDao,
		"public.mib_to_module_compliance":               dao.GetAllMibToModuleComplianceDao,
		"public.mib_to_module_identity":                 dao.GetAllMibToModuleIdentityDao,
		"public.mib_to_notification_group":              dao.GetAllMibToNotificationGroupDao,
		"public.mib_to_notification_type":               dao.GetAllMibToNotificationTypeDao,
		"public.mib_to_object_group":                    dao.GetAllMibToObjectGroupDao,
		"public.mib_to_object_identifier":               dao.GetAllMibToObjectIdentifierDao,
		"public.mib_to_object_identity":                 dao.GetAllMibToObjectIdentityDao,
		"public.mib_to_object_type":                     dao.GetAllMibToObjectTypeDao,
		"public.mib_to_sequence":                        dao.GetAllMibToSequenceDao,
		"public.mib_to_textual_convention":              dao.GetAllMibToTextualConventionDao,
		"public.mib_to_trap_type":                       dao.GetAllMibToTrapTypeDao,
		"public.device_indicator":                       dao.GetAllDeviceIndicatorDao,
		"public.param_indicator":                        dao.GetAllParamIndicatorDao,
		"public.mapping":                                dao.GetAllMappingDao,
		"public.device_component":                       dao.GetAllDeviceComponentDao,
		"public.device_component_mapping":               dao.GetAllDeviceComponentMappingDao,
		"public.configuration":                          dao.GetAllConfigurationDao,
		"public.default_configuration":                  dao.GetAllDefaultConfigurationDao,
		"public.threshold":                              dao.GetAllThresholdDao,
		"public.device_snmp":                            dao.GetAllDeviceSnmpDao,
		"public.result":                                 dao.GetAllResultDao,
		"public.affected_threshold":                     dao.GetAllAffectedThresholdDao,
		"public.affected_param":                         dao.GetAllAffectedParamDao,
		"public.config_in_process":                      dao.GetAllConfigInProcessDao,
	}
	wg.Add(1)
	go func() {
		var constraintsPath string
		var constraintsFile *os.File
		var errWrite error
		var errClose error
		constraintsPath = filepath.Join(outputDir, "constraints.sql")
		constraintsFile, _ = os.Create(constraintsPath)
		if constraintsFile != nil {
			_, errWrite = constraintsFile.WriteString(constraintsSQL)
			if errWrite != nil {
				logger.Error("Failed to write to file constraints.sql: %v", errWrite)
			}
			errClose = constraintsFile.Close()
			if errClose != nil {
				logger.Error("Failed to close file constraints.sql: %v", errClose)
			}
		}
		ch <- rawQueryResult{tableName: "public.constraints", data: []string{}}
		wg.Done()
	}()
	for tName, fn = range callers {
		wg.Add(1)
		go func(tableName string, fetchFunc any) {
			var fVal reflect.Value
			var out []reflect.Value
			var dataSlice any
			var fetchErr any
			fVal = reflect.ValueOf(fetchFunc)
			out = fVal.Call(inArgs)
			dataSlice = out[0].Interface()
			fetchErr = out[1].Interface()
			if fetchErr != nil {
				logger.Error("Error fetching %s", tableName)
			}
			executeTableExport(outputDir, tableName, dataSlice)
			ch <- rawQueryResult{tableName: tableName, data: dataSlice}
			wg.Done()
		}(tName, fn)
	}
	go func() {
		wg.Wait()
		close(ch)
	}()
	for item = range ch {
		var vVal reflect.Value
		vVal = reflect.ValueOf(item.data)
		results = append(results, tablePrintResult{tableName: item.tableName, rowCount: vVal.Len()})
	}
	sort.Slice(results, func(i int, j int) bool {
		var isGreater bool
		isGreater = results[i].tableName > results[j].tableName
		return !isGreater
	})
	idx = len(results)
	logger.Info("Export of data from all DB tables to SQL scripts located in the /sql directory was completed successfully")
	logger.Info("Export statistics:")
	logger.Info("%-50s-+-%s\n", "--------------------------------------------------", "----")
	logger.Info("%-50s | %s\n", "Table name", "Rows")
	logger.Info("%-50s-+-%s\n", "--------------------------------------------------", "----")
	for idx > 0 {
		idx--
		outputItem = results[len(results)-1-idx]
		logger.Info("%-50s | %d\n", outputItem.tableName, outputItem.rowCount)
	}
	logger.Info("%-50s-+-%s\n", "--------------------------------------------------", "----")
	return nil
}

func executeTableExport(outputDir string, tableName string, dataSlice any) {
	var vVal reflect.Value
	var total int
	var sb strings.Builder
	var schema string
	var batchSize int
	var i int
	var hasID bool
	var f *os.File
	var filePath string
	var finalSQL string
	var errWrite error
	var errClose error
	vVal = reflect.ValueOf(dataSlice)
	total = vVal.Len()
	schema = tableSchemas[tableName]
	sb.WriteString(schema)
	sb.WriteString("\n\n")
	batchSize = 5000
	i = 0
	hasID = false
	if total > 0 {
		var firstElem reflect.Value
		var t reflect.Type
		var fIdx int
		firstElem = vVal.Index(0)
		t = firstElem.Type()
		fIdx = t.NumField()
		for fIdx > 0 {
			var field reflect.StructField
			fIdx--
			field = t.Field(fIdx)
			if strings.ToLower(field.Name) == "id" {
				var fKind reflect.Kind
				fKind = field.Type.Kind()
				if fKind == reflect.Int16 || fKind == reflect.Int32 || fKind == reflect.Int64 || fKind == reflect.Int {
					hasID = true
				}
			}
		}
	}
	for total > i {
		var chunkEnd int
		var vals []string
		var fields []string
		var insertQuery string
		var j int
		chunkEnd = i + batchSize
		if chunkEnd > total {
			chunkEnd = total
		}
		vals = make([]string, 0, chunkEnd-i)
		for j = i; chunkEnd > j; j++ {
			var rowVal reflect.Value
			var rowType reflect.Type
			var fCount int
			var fIter int
			var rowFields []string
			rowVal = vVal.Index(j)
			rowType = rowVal.Type()
			fCount = rowVal.NumField()
			rowFields = make([]string, 0, fCount)
			fields = make([]string, 0, fCount)
			fIter = fCount
			for fIter > 0 {
				var structField reflect.StructField
				var fieldVal reflect.Value
				var tag string
				var sqlVal string
				var directIdx int
				fIter--
				directIdx = fCount - 1 - fIter
				structField = rowType.Field(directIdx)
				fieldVal = rowVal.Field(directIdx)
				tag = structField.Tag.Get("db")
				if tag == "" {
					continue
				}
				fields = append(fields, fmt.Sprintf("\"%s\"", tag))
				sqlVal = formatReflectValue(fieldVal)
				rowFields = append(rowFields, sqlVal)
			}
			vals = append(vals, fmt.Sprintf("(%s)", strings.Join(rowFields, ", ")))
		}
		if len(vals) > 0 {
			insertQuery = fmt.Sprintf("INSERT INTO %s (%s)\nVALUES %s;\n\n", tableName, strings.Join(fields, ", "), strings.Join(vals, ",\n       "))
			sb.WriteString(insertQuery)
		}
		i = chunkEnd
	}
	if hasID {
		sb.WriteString(fmt.Sprintf("SELECT SETVAL(PG_GET_SERIAL_SEQUENCE('%s', 'id'), COALESCE(MAX(\"id\"), 1))\nFROM %s;", tableName, tableName))
	}
	finalSQL = sb.String()
	finalSQL = strings.TrimRight(finalSQL, "\n\r ")
	filePath = filepath.Join(outputDir, fmt.Sprintf("%s.sql", tableName))
	f, _ = os.Create(filePath)
	if f != nil {
		_, errWrite = f.WriteString(finalSQL)
		if errWrite != nil {
			logger.Error("Failed to write to file %s.sql: %v", tableName, errWrite)
		}
		errClose = f.Close()
		if errClose != nil {
			logger.Error("Failed to close file %s.sql: %v", tableName, errClose)
		}
	}
}

func formatReflectValue(v reflect.Value) string {
	var kind reflect.Kind
	var tName string
	kind = v.Kind()
	tName = v.Type().Name()
	if tName == "NullString" {
		if v.FieldByName("Valid").Bool() {
			return fmt.Sprintf("'%s'", strings.ReplaceAll(v.FieldByName("String").String(), "'", "''"))
		}
		return "NULL"
	}
	if tName == "NullInt16" {
		if v.FieldByName("Valid").Bool() {
			return fmt.Sprintf("%d", v.FieldByName("Int16").Int())
		}
		return "NULL"
	}
	if tName == "NullInt32" {
		if v.FieldByName("Valid").Bool() {
			return fmt.Sprintf("%d", v.FieldByName("Int32").Int())
		}
		return "NULL"
	}
	if tName == "NullInt64" {
		if v.FieldByName("Valid").Bool() {
			return fmt.Sprintf("%d", v.FieldByName("Int64").Int())
		}
		return "NULL"
	}
	if tName == "NullFloat64" {
		if v.FieldByName("Valid").Bool() {
			return fmt.Sprintf("%f", v.FieldByName("Float64").Float())
		}
		return "NULL"
	}
	if tName == "NullBool" {
		if v.FieldByName("Valid").Bool() {
			return fmt.Sprintf("%t", v.FieldByName("Bool").Bool())
		}
		return "NULL"
	}
	if tName == "NullTime" {
		if v.FieldByName("Valid").Bool() {
			var tm time.Time
			tm = v.FieldByName("Time").Interface().(time.Time)
			return fmt.Sprintf("'%s'", tm.Format("2006-01-02 15:04:05"))
		}
		return "NULL"
	}
	if tName == "UUID" {
		var uid uuid.UUID
		uid = v.Interface().(uuid.UUID)
		return fmt.Sprintf("'%s'", uid.String())
	}
	if kind == reflect.Slice && v.Type().Elem().Kind() == reflect.Uint8 {
		var b []byte
		b = v.Bytes()
		if b == nil {
			return "NULL"
		}
		return fmt.Sprintf("'%s'", strings.ReplaceAll(string(b), "'", "''"))
	}
	if kind == reflect.Slice && v.Type().Elem().Kind() == reflect.String {
		var sliceLen int
		var sIdx int
		var parts []string
		sliceLen = v.Len()
		if sliceLen == 0 {
			return "NULL"
		}
		parts = make([]string, sliceLen)
		sIdx = sliceLen
		for sIdx > 0 {
			sIdx--
			parts[sIdx] = fmt.Sprintf("\"%s\"", strings.ReplaceAll(v.Index(sIdx).String(), "\"", "\\\""))
		}
		return fmt.Sprintf("'{%s}'", strings.Join(parts, ","))
	}
	if kind == reflect.Slice && v.Type().Elem().Kind() == reflect.Ptr {
		var sliceLen int
		var sIdx int
		var parts []string
		sliceLen = v.Len()
		if sliceLen == 0 {
			return "NULL"
		}
		parts = make([]string, sliceLen)
		sIdx = sliceLen
		for sIdx > 0 {
			sIdx--
			var pElem reflect.Value
			pElem = v.Index(sIdx)
			if pElem.IsNil() {
				parts[sIdx] = "NULL"
			} else {
				parts[sIdx] = fmt.Sprintf("\"%s\"", strings.ReplaceAll(pElem.Elem().String(), "\"", "\\\""))
			}
		}
		return fmt.Sprintf("'{%s}'", strings.Join(parts, ","))
	}
	if kind == reflect.String {
		return fmt.Sprintf("'%s'", strings.ReplaceAll(v.String(), "'", "''"))
	}
	if kind == reflect.Int16 || kind == reflect.Int32 || kind == reflect.Int64 || kind == reflect.Int {
		return fmt.Sprintf("%d", v.Int())
	}
	if kind == reflect.Bool {
		return fmt.Sprintf("%t", v.Bool())
	}
	return "NULL"
}
