package dao

var tablesQueue = []string{
	"public.changelog",
	"public.polling_protocol",
	"public.access",
	"public.version_snmp",
	"public.auth_protocol_snmp",
	"public.privacy_protocol_snmp",
	"public.oid_type",
	"public.logic_operator",
	"public.alarm_level",
	"public.var_type",
	"public.polling_frequency",
	"public.oid_access",
	"public.oid_status",
	"public.asn1_type",
	"public.vendor",
	"public.agent_capabilities",
	"public.agent_capabilities_module",
	"public.agent_capabilities_module_notification",
	"public.agent_capabilities_module_object",
	"public.choice",
	"public.explicit",
	"public.implicit",
	"public.import",
	"public.mib",
	"public.module_compliance",
	"public.module_compliance_module",
	"public.module_compliance_module_group",
	"public.module_compliance_module_object",
	"public.module_identity",
	"public.notification_group",
	"public.notification_type",
	"public.object_group",
	"public.object_identifier",
	"public.object_identity",
	"public.object_type",
	"public.revision",
	"public.sequence",
	"public.textual_convention",
	"public.trap_type",
	"public.mib_to_agent_capabilities",
	"public.mib_to_choice",
	"public.mib_to_explicit",
	"public.mib_to_implicit",
	"public.mib_to_import",
	"public.mib_to_module_compliance",
	"public.mib_to_module_identity",
	"public.mib_to_notification_group",
	"public.mib_to_notification_type",
	"public.mib_to_object_group",
	"public.mib_to_object_identifier",
	"public.mib_to_object_identity",
	"public.mib_to_object_type",
	"public.mib_to_sequence",
	"public.mib_to_textual_convention",
	"public.mib_to_trap_type",
	"public.oid",
	"public.component",
	"public.param",
	"public.component_param",
	"public.device_indicator",
	"public.param_indicator",
	"public.mapping",
	"public.device_component",
	"public.device_component_mapping",
	"public.configuration",
	"public.default_configuration",
	"public.threshold",
	"public.device_snmp",
	"public.result",
	"public.affected_threshold",
	"public.affected_param",
	"public.config_in_process",
}

const (
	componentStartIdx       = 56
	pluginStartIdx          = 57
	deviceComponentStartIdx = 62
)
